{literal}
<script type="text/javascript">
var cur_date=0,js_date=0,diff_date=0;
cur_date={/literal}{$smarty.now}{literal};
js_date=(new Date().getTime())/ 1000;
diff_date=Math.floor(js_date-cur_date);
$("#menu_home").addClass("active");
</script>
{/literal}
<div class="container">
	<!-- start, status -->
		<div class="row-fluid">		
			<div id="getstarted" class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<h4>GET OFF TO A GOOD START!</h4>
				<p class="pull-right"><a href="#help" class="btn scroll">How does it work ?</a></p> 
				<ul class="unstyled">
					<li><i class="icon icon-ok"></i> Only 1 writer selected per mission</li>
					<li><i class="icon icon-ok"></i> Only start writing once you have been selected by Edit-place or the client</li>
					<li><i class="icon icon-ok"></i> Follow the editorial guidelines/brief and the deadlines</li>
			   </ul>
			</div>		 
			<!-- start, get contributor status -->
			<section id="status">
				<div class="row-fluid">
					<div class="profilehead-mod">
						<div class="span5 profile-name">
							<a href="/contrib/private-profile" class="pull-left imgframe">
								<img src="{$contrib_home_picture}" title="{$client_email}" class="media-object">
							</a>
							{if $profileType eq 'senior'}
								<span data-original-title="Senior" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Senior</span>
							{elseif $profileType eq 'junior'}
								<span data-original-title="Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Junior</span>
							{elseif $profileType eq 'sub-junior'}
								<span data-original-title="Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Beginner</span>	
							{/if}
							<h3>{$client_email}</h3>
						</div>
						
						<div class="span3 stat">
							<div class="progress progress-success">
							<div class="bar" style="width: {$profile_percentage}%"></div>
							</div>
							Your profile is <strong>{$profile_percentage}%</strong> complete
							<div class="btn-link"><a href="/contrib/modify-profile">Update</a></div>
						</div>

						<div class="span2 stat">
							<p>Ongoing contributions</p>
							<p class="num-large"><a href="/contrib/ongoing">{$participation_Count}</a></p>
						</div>
						
						<div class="span2 stat"><p>Total royalties</p><p class="num-large"><a href="/contrib/royalties">
						{$userRoyalty[0].royalty|zero_cut:2} &{$userRoyalty[0].currency};
						{if $userRoyalty[0].royalty && $userRoyalty[1].royalty } , {/if}
						{if $userRoyalty[1].royalty}
								{$userRoyalty[1].royalty|zero_cut:2} &{$userRoyalty[1].currency};
						{/if}
						</a></p></div>
					</div>
				</div>

			</section>
			  <!-- end, contributor status --> 
		 
			<div class="row-fluid"> 
				<div class="span8">
						
					<section id="quick-classified">
						<div class="mod">
							<span class="pull-right icon-waiting-quote" data-original-title="Don't waste any time! Make an offer quickly" rel="tooltip"></span>
							<h4>RESPOND TO THESE NEW OFFERS</h4>
							<table class="table table-hover">
								
								{if $recent_AO_Offers|@count gt 0}
									{foreach item=offer from=$recent_AO_Offers}										
										<tr>
											{if $offer.ao_type eq 'correction'}
												<td>
													{if $offer.missiontest eq 'yes'}
														<span class="label label-test-mission" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Test Mission</span>
													{else}
														<span class="label label-correction" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Mission</span>
													{/if}	
												{if $offer.view_to eq 'sc'}
													<span data-original-title="Available to Seniors" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $offer.view_to eq 'jc'}
													<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $offer.view_to eq 'jc0'}
													<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
												{/if}
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=correction&mission_identifier={$offer.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $offer.title|strlen gt 75} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>{$offer.title|truncate:75:"...":true|stripslashes}</span> {$offer.picon} </a></td>
											
											{elseif $offer.ao_type eq 'poll_premium'}
												<td><span class="label label-quote-premium" data-original-title="This offer may become a Premium mission" rel="tooltip" data-placement="right">Premium quote</span>
												{if $offer.contributors eq '0'}
													<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $offer.contributors eq '1'}
													<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $offer.contributors eq '3'}
													<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
												{/if}
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=poll_premium&mission_identifier={$offer.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $offer.title|strlen gt 75} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>{$offer.title|truncate:75:"...":true|stripslashes}</span></a></td>
											{elseif $offer.ao_type eq 'poll_nopremium'}
												<td><span class="label label-quote" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Freedom Quote</span>
												{if $offer.contributors eq '0'}
													<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $offer.contributors eq '1'}
													<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $offer.contributors eq '3'}
													<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
												{/if}
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=poll_nopremium&mission_identifier={$offer.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $offer.title|strlen gt 75} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>{$offer.title|truncate:75:"...":true|stripslashes}</span></a></td>	
											{elseif $offer.premium_option}	
												<td>
													{if $offer.missiontest eq 'yes'}
														<span class="label label-test-mission" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right"><i class="icon-star icon-white"></i>  Staffing</span>
													{else}
														<span class="label label-premium" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Premium Mission</span>
													{/if}

													
												{if $offer.view_to eq 'sc'}
													<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
												{elseif $offer.view_to eq 'jc'}
													<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
												{elseif $offer.view_to eq 'jc0'}
													<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
												{/if}
												</td>
												<td class="title">
													{if $offer.missiontest eq 'yes'}
														<a href="/recruitment/participation-challenge?recruitment_id={$offer.deliveryid}"><span {if $offer.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>
															<b>{$offer.title|truncate:70:"...":true|stripslashes}</b>
															{*<div class="muted">Vous &eacute;crirez {$offer.mission_volume} {$offer.product_type_name} d'achats en {$offer.language_name}</div>*}
														</a>
													{else}
														<a href="/contrib/article-details?misson_type=premium&mission_identifier={$offer.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $offer.title|strlen gt 70} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>{$offer.title|truncate:70:"...":true|stripslashes}</span> {$offer.picon} {$offer.qicon}</a>
													{/if}	
												</td>
											{elseif !$offer.premium_option}			
												<td>
													{if $offer.missiontest eq 'yes'}
														<span class="label label-test-mission" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right"><i class="icon-star icon-white"></i>  Staffing</span>
													{else}
														<span class="label label-quote" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Freedom Mission</span>
													{/if}	
													{if $offer.view_to eq 'sc'}
														<span data-original-title="Available to Senior" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
													{elseif $offer.view_to eq 'jc'}
														<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
													{elseif $offer.view_to eq 'jc0'}
														<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
													{/if}
												</td>
												<td class="title"><a href="/contrib/article-details?misson_type=nopremium&mission_identifier={$offer.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $offer.title|strlen gt 70} rel="tooltip" align="top" data-original-title="{$offer.title|stripslashes}"{/if}>{$offer.title|truncate:70:"...":true|stripslashes}</span> {$offer.picon} {$offer.qicon}</a></td>
											{/if}
											<td class="countdown">
												{if $offer.ao_type eq 'correction'}
													<span id="time_{$offer.articleid}-correction_{$offer.timestamp}">
														<span id="text_{$offer.articleid}-correction_{$offer.timestamp}">{$offer.timestamp}</span>
													</span>
												{else}
												<span id="time_{$offer.articleid}_{$offer.timestamp}">
													<span id="text_{$offer.articleid}_{$offer.timestamp}">{$offer.timestamp}</span>
												</span>
												{/if}	
												
											</td>
										</tr>
										
									{/foreach}
								{else}	
									<tr>
										<td colspan="3">
											<span class="no-data">There are no calls for orders at the moment</span>
										</td>	
									</tr>	
								{/if}					

							</table>
							
							{if $recent_AO_Offers|@count gt 0}
								<a href="/contrib/aosearch"><div class="btn btn-block btn-small">See all the offers</div></a>
							{/if}	
							
						</div>

					 </section>
			 
			 
				</div>
			
				<div class="span4">
				<!--  right column  -->		  
					<aside>				  
						<div class="aside-bg" style="padding:0px">
							<!--<div class="aside-block" id="browse-by-cat">
								<h4>Recherche par cat&eacute;gorie</h4>
								<ul class="nav nav-tabs nav-stacked">
									{foreach key=key item=category from=$ep_categories_list}
										<li><a href="/contrib/aosearch?search_category={$key}">
										{if $ep_category_articles_count.$key gt 0}
											<span class="badge badge-warning pull-right">{$ep_category_articles_count.$key}</span>
										{else}		
											<span class="badge pull-right">{$ep_category_articles_count.$key}</span>
										{/if}	
										{$category}</a></li>									
									{/foreach}	
								</ul>	
							</div>-->
							<div id="ao-next" class="aside-block">
								<div class="pull-center">
									<h4 class="date"><span>Tomorrow,</span> {$publish_date} <i class="icon-calendar icon-white"></i></h4>
									<div class="main">
										<span class="nb"><a href="/contrib/aosearch#soon">{$upcoming_count}</a></span><a href="/contrib/aosearch#soon"> NEW OFFERS OPEN TO CONTRIBUTIONS</a>
									</div>
								</div>
								You can already : 
								<ul>
								  <li>Read about these offers</li>
								  <li>Receive an alert once contributions are open</li>
								</ul>
								<div class="pull-center"><a href="/contrib/aosearch#soon" class="btn btn-small">See the next offers</a></div>
							</div>
						</div>				  
					</aside>
				</div>
			</div>
	 </div>
</div>		
