<div class="container">
	<br>
{if $missionDetails | @count gt 0}
	{foreach from=$missionDetails item=article name=details}	
	<ul class="breadcrumb">
	<li><a href="/contrib/home">Home</a> <span class="divider">/</span></li>
	<li><a href="/contrib/ongoing">My contributions</a> <span class="divider">/</span></li>
	<li class="active">{$article.title}</li>
	</ul> 
	<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">×</button>
		<i class="icon-ok icon-white"></i> Congratulations {$client_email} ! You have been selected as a writer for this mission. Please respect deadlines. 
	</div>
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span7">
				{if $article.missiontest eq 'yes'}
					<span class="label label-test-mission">Proofreading Test Mission</span>
				{else}
					<span class="label label-correction">Proofreading Mission</span>
				{/if}
				<h1>{$article.title}</h1>
			</div>
			<div class="span2 stat">
				<p>Delivery deadline</p>
				<!-- add classname "less24" if time is < 24h  -->
				<!-- p class="num-large less24">Livrée</p-->
				{if $article.status eq 'bid' OR $article.status eq 'disapproved' }
					<p class="num-large less24">
						<span id="dtime_{$article.article_id}_{$article.corrector_submit_expires}">
							<span id="dtext_{$article.article_id}_{$article.corrector_submit_expires}">{$article.corrector_submit_expires}</span>
						</span>
					</p>
				{else}
					<p class="num-large less24" style="font-size:18px">{$article.status_trans}</p>
				{/if}	
			</div>
			<div class="span2 stat">
				<p>Rate</p>
				<p class="num-large">{$article.price_corrector} 
				{if $article.currency eq 'euro'	}
						&euro;
					{else}
						&pound;
					{/if}
				</p>
			</div>
			<div class="span1 stat">
				<div class="icon-comment-large new"><a href="#comment" class="scroll" id="comment_count">{$commentDetails|@count}</a></div>
				<!--  to active if new comment, add classname "new" -->
				<!--div class="icon-comment-large new"><a href="#comment">3</a></div-->
			</div>
		</div>
	</section>
	<!-- end, summary --> 
	<div class="row-fluid"> 
		<div class="span9">
			<section id="corrector">
				<div class="mod pull-center">
					<div class="icon_corrector"></div>
					<h4>Welcome to Your Proofreading Space </h4>
					<p>Please read the editorial guidelines/briefs carefully before starting</p>
					<div class="row-fluid file-management-cont"> 
						<div class="row-fluid">  
							<table class="table well span11 offset1" style="margin-left: 4%">
								<thead>
									<tr>
										<th class="span6">Article to proofread</th>
										<th class="span1">Writer</th>
										<th class="span3" style="text-align:center">Amendment</th>
										<th class="span1">Size</th>
										<th class="span1"></th>
									</tr>
								</thead>
								<tbody>
								{foreach item=varticle from=$AllVersionArticles name=articledetails}
									<tr>
										<td class="span6"><i class="icon-file"></i> <a href="/contrib/download-version-article?processid={$varticle.id}">{$varticle.article_name}</a></td>										
										<td class="span1">{$varticle.first_name}</td>
										<td class="span3" style="text-align:center">{$varticle.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
										<td class="span1 muted">{$varticle.file_size}</td>
										<td class="span1"><a href="/contrib/download-version-article?processid={$varticle.id}" data-original-title="Download" rel="tooltip" class="btn btn-small"><i class="icon-download"></i></a></td>
									</tr>
								{/foreach}									
								</tbody>
							</table> 
						</div>
						{if $article.status eq 'bid' OR $article.status eq 'disapproved'}
						<a class="btn btn-primary" data-target="#fix-article" data-toggle="modal" role="button" href="/contrib/corrector-article-popup?cparticipation_id={$CorrectorParticipationId}&article_id={$article.article_id}"><i class="icon-pencil icon-white"></i> Proofread the article</a>
						{/if}
					</div>					
				</div>
			</section>
			<section id="a_o">
				<div class="mod">
					<div class="summary clearfix">
						<h4>Project Details</h4>
						<ul class="unstyled">
							<li><strong>Proofreading</strong> <span class="bullet">&#9679;</span></li>
							<li> Language : <img src="/FO/images/shim.gif" class="flag flag-{$article.language}"> <span class="bullet">&#9679;</span></li>
							<li> Category : {$article.category} <span class="bullet">&#9679;</span></li>
							<li> Nb. of words : {$article.num_min} - {$article.num_max} / article
							<!--<span class="bullet">&#9679;</span></li>
							<li><a class="scroll" href="#comment"><i class="icon-comment"></i> {$commentDetails|@count}</a></li>-->
							{if $article.spec_exists eq 'yes'}
								<li class="pull-right"><a href="/contrib/download-file?type=correctionbrief&article_id={$article.article_id}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> Download the client brief</a></li>
							{/if}
						</ul>
					</div>
				</div>
			</section>
			{include file="Contrib/article-comments.phtml"}
		</div>
		<div class="span3">
		<!--  right column  -->
			<aside>
				<div class="aside-bg">
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>The Writer</h4>
							<a href="/contrib/public-profile?user_id={$article.writer}" data-target="#viewProfile-ajax" data-toggle="modal" role="button"><img src="{$article.writer_pic_profile}" alt="{$article.writer_name}"></a>							
							<p class="editor-name">{$article.writer_name}</p>
						</div>
					</div>


					<div class="aside-block" id="garantee">
						<h4>Your Guarantees</h4>
						<dl>
							<dt><span class="umbrella"></span>Edit-place is your mediator</dt>
							<dd>In case of disputes/issues (delivery deadline, article rewrite/amendment, refund...)</dd>
							<dt><span class="locked"></span>Secure payment</dt>
							<dd>Our online payment solution guarantees a hassle-free transaction</dd>
						</dl>
					</div>
				</div>
			</aside>
		</div>
	</div>
	{/foreach}
{/if}
</div>
<link rel="stylesheet" type="text/css" href="{$livesite}/FO/css/common/bootstrap-wysihtml5.css"></link>
<script src="{$livesite}/FO/script/common/wysihtml5-0.3.0.min.js"></script>
<script src="{$livesite}/FO/script/common/bootstrap-wysihtml5.js"></script> 
<!--  ratings -->
<script type="text/javascript" charset="utf-8" src="{$livesite}/FO/script/common/jquery.raty.min.js"></script>
{literal}
<script type="text/javascript">
var cur_date=0,js_date=0,diff_date=0;
cur_date={/literal}{$smarty.now}{literal};
js_date=(new Date().getTime())/ 1000;
diff_date=Math.floor(js_date-cur_date);
	$("#menu_ongoing").addClass("active");
	startMissionTimer('dtime','dtext');	
function refreshModel(cpartid, artid)
{   //alert('hey');
    var href="/contrib/corrector-article-popup?cparticipation_id="+cpartid+"&article_id="+artid+" ";
    $("#fix-article").removeData('modal');
    $('#fix-article .modal-body').load(href);
    $("#fix-article").modal();
    $(".modal-backdrop:gt(0)").remove();
}
</script>
{/literal}
<!-- ***** Modal collections -->
<!-- ajax use start -->
<div id="fix-article" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Proofreading of article</h3>
	</div>
	<div class="modal-body">
	</div>
</div>
	<!-- ajax use start -->
	<div id="viewProfile-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 id="myModalLabel">Public Profile</h3>
			</div>
		<div class="modal-body">
		</div>
	</div>
	<!-- ajax use end -->