{if $smarty.get.profile eq 'invoice'}
<script type="text/javascript" src="/FO/script/contrib/profile-validate-invoice.js"></script>
{else}
<script type="text/javascript" src="/FO/script/contrib/profile-validate.js"></script>
{/if}	
{literal}
<script type="text/javascript">
	$("#menu_profile").addClass("active");
/**profile pic uploading**/
$(function(){
		var btnUpload=$('.customfile');
		var status=$('#file_name');
		new AjaxUpload(btnUpload, {
			action: 'uploadprofilepic',
			name: 'uploadpic',
			onSubmit: function(file, ext){
				 if (! (ext && /^(jpg|jpeg|gif|png)$/.test(ext))){ 
                    // extension is not allowed 
					status.text("Please upload JPG,PNG and GIF files only.").css('color','#FF0000');
					return false;
					}

				 /*if (! (ext && /^(doc|docx|rtf)$/.test(ext))){ 
                    // extension is not allowed 
					status.html('Only doc,docx,rtf files are allowed').css('color','#FF0000');
					return false;
					}*/
				status.html('<img src="/FO/images/icon-image.gif" /> Chargement..');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.text('');
				$('#file_name').html('');
				
				//Add uploaded file to list
				var obj = $.parseJSON(response);
				var approot="/FO/";
				
				if(obj.status=="success"){
					$('#spec_file_name').val(file);
					
					$('#Cropimage').modal();
					var top=$(window).scrollTop();
					var box_top=$('#Cropimage').css('top', (parseInt(60) + ((top*2)/$(window).height())) + '%');
					//alert(approot+obj.path+obj.identifier+"_crop."+obj.ext+ '?' + (new Date()).getTime());
					$("#cropbox").attr('src','#');
					$(".jcrop-holder").remove();
					$("#cropbox").removeData('Jcrop');
					$("#cropbox").attr("src",approot+obj.path+obj.identifier+"_crop."+obj.ext+ '?' + (new Date()).getTime());
					$("#cropbox").show();
					$('#cropbox').Jcrop({
						aspectRatio: 1,
						addClass: 'jcrop-dark',
						setSelect: [ 60, 110, 150, 200 ],
						onSelect: updateCoords
					});
							
					if(file.length>25)
					$('#file_name').html(file.substr(0,25)+".. Uploaded").css('color','#006600');
					else
					$('#file_name').html(file+" Uploaded").css('color','#006600');
					
					//window.setTimeout('location.reload()', 10);
					
					
					
				}
				else if(obj.status=="smallfile"){
				
					$('#file_name').html("L'image est trop petite, merci d'en uploader une autre").css('color','#FF0000');
				}
				else{
					$('#file_name').html('Error in upload').css('color','#FF0000');
				}
			}
		});
				
		jQuery('img').each(function(){
			jQuery(this).attr('src',jQuery(this).attr('src')+ '?' + (new Date()).getTime());
		});		
	});	

	/**toggle for payment infos**/
	 $('input[type=radio]').live('click', function () {
		
		var payment_type = $("input:radio[name ='payment_type']:checked").val();
		var country = $("#country").val();		
		var payinfo=$('input:radio[name=payinfo]:checked').val();
		
		if (this.checked && $(this).val() == 'ssn') 
		{		
			$(this).addClass('in');
			$("#siretNum").removeClass('in');
			$("#siretNum").css('height','0px');
			
			if(payment_type=='virement' && country!=101)
			{
				$("#c_out_uk").show();
				$("#c_france").hide();
			}
			else if(payment_type=='virement')			
			{
				$("#c_out_uk").hide();
				$("#c_france").show();
			}
			
			if(country!=101)
			{
				$("#cheque_radio").hide();
				$("#cheque_radio").find("input:radio:checked").removeProp('checked');
			}	
			else
				$("#cheque_radio").show();
		}
		else if (this.checked && $(this).val() == 'comp_num') 
		{		
			$(this).addClass('in');
			$("#national-InsuranceNum").removeClass('in');
			$("#national-InsuranceNum").css('height','0px');
			
			if(payment_type=='virement'  && country!=101)
			{
				$("#c_out_uk").show();
				$("#c_france").hide();
			}
			else if(payment_type=='virement')			
			{
				$("#c_out_uk").hide();
				$("#c_france").show();
			}
			if(country!=101)
			{
				$("#cheque_radio").hide();
				$("#cheque_radio").find("input:radio:checked").removeProp('checked');
			}	
			else
				$("#cheque_radio").show();
		}	
		else if (this.checked && $(this).val() == 'out_uk') 
		{		
			$("#national-InsuranceNum").removeClass('in');
			$("#national-InsuranceNum").css('height','0px');
			$("#siretNum").removeClass('in');
			$("#siretNum").css('height','0px');
			
			
			if(payment_type=='virement'  || country!=101)
			{
				$("#c_out_uk").show();
				$("#c_france").hide();
			}
			else if(payment_type=='virement')			
			{
				$("#c_out_uk").hide();
				$("#c_france").show();
			}
			$("#cheque_radio").hide();
			$("#cheque_radio").find("input:radio:checked").removeProp('checked');
			
		}
		else if (this.checked && $(this).val() == 'virement') 
		{
			var payinfo = $("input:radio[name ='payinfo']:checked").val();
			if(payinfo=='out_uk' || country!=101)
			{
				$("#c_out_uk").show();
				$("#c_france").hide();
			}
			else			
			{
				$("#c_out_uk").hide();
				$("#c_france").show();
			}
		}
		else if (this.checked && $(this).val() == 'paypal' || this.checked && $(this).val() == 'cheque' ) 
		{
			$("#c_out_uk").hide();
			$("#c_france").hide();
		}
		
	});
	
	
</script>
{/literal}
<div class="container">
	 <!-- ajax use start -->
					<div id="Cropimage" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="cropimageLabel" aria-hidden="true">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3 id="cropimageLabel">Redimensionner l'image</h3>
						</div>
						<div class="modal-body">
							{include file="Contrib/profile_image_crop.phtml"}
						</div>
					</div>
					<!-- ajax use end -->
    <div class="row-fluid">
		{if $actionmessages[0]}
			<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">&times;</button>
				<i class="icon-ok icon-white"></i> {$actionmessages[0]}.
			</div>  
		{/if}
		{if $selected_ao_count}
			<div class="span12" style="color:#F47D31;"><h2>Amend Profile: Complete your profile to access your selection</h2></div>
		{else}	
			<div class="span12"><h1>Amend profile
				<div class="pull-right">
					<a href="/contrib/private-profile" class="btn btn-small"><i class="icon-arrow-left"></i> Go back to my private profile</a>
					{if $cv_exists eq 'yes'}
						<a class="btn btn-small" href="/contrib/download-file?type=cv"><i class="icon-briefcase"></i> Mon CV</a>
					{/if}			
				</div>
				</h1>
			</div>
		{/if}	
	</div>
		
	<section id="skills-form">
		<form class="form-horizontal" method="POST" action="/contrib/save-profile/" id="contribProfile">
			<div class="mod">
				<div class="row-fluid">
				<!-- identity -->
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My ID <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form">
								<label>
								<select class="select-large" name="initial" id="initial">
									<option value="">I am</option>
									<option value="mr" {if $civ=='mr'} selected{/if}>Male</option>
									<option value="ms" {if $civ=='mrs' || $civ=='ms' } selected{/if}>Female</option>
								</select>
								</label>
								<label><input type="text" placeholder="My first name" class="inline input-large" value="{$fname}" name="first_name" id="first_name"></label>
								<label><input type="text" placeholder="My last name" class=" input-large" value="{$lname}" name="last_name" id="last_name"></label>
							</div>
						</div>
					</div>
					<!-- birthday -->

					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My date of birth <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form-inline">
								<label>
									{html_select_date end_year="1910" start_year='+0' field_order="DMY" time=$dob class="input-small" field_separator="</label>&nbsp;<label>"}
								</label>	
							</div>
						</div>
					</div>
				<!--Picture --> 
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Profile photo</strong></label>
						<div class="controls span8 container-field">
							<div id="changePicture">
								<div class="span2">
									<div class="editor-container pull-left">
										<a href="/contrib/modify-profile" class="imgframe-large"><img id="profilepic" title="{$client_eMayl}" src="{$profile_image}"></a>
									</div>
								</div>
								<div class="span9 offset1">
									<p>Update your photo :</p>
									<input type="file" class="span9" name="file" id="filePJ">
									<span id="file_name" class="help-block"></span>
									<span class="help-block">Image size: 90x90 </span>
								</div>
							</div>
						</div>  
					</div>
					
				<!-- about me -->  
				<div class="control-group">
				<label class="control-label span2 offset1" for=""><strong>Presentation text</strong></label>
				<div class="controls span8">
				<textarea class="span12" placeholder="100 characters minimum" name="self_details" id="self_details" >{$self_details}</textarea>
				</div>   
				</div>

				</div>
			</div>   


			<!-- Start, Languages module -->    
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Languages &amp; level <span class="error">*</span></strong></label>
						<div class="controls span8">    
							<select class="span5" name="language" id="language">
								<option value=''>Mother tongue</option>
								{html_options  options=$ep_language_list selected=$profile_mother_language}
							</select>
						</div>
						<div class="controls span8">
							{if $language_more|@count gt 0}
								{foreach from=$language_more key=lang item=percent name="moreLanguage}
									{assign var=lang_index value=$smarty.foreach.moreLanguage.index}
										<!-- Start, new language row -->
										<div class="addmore" id="language_more_{$lang_index}">  
											<button  class="close" type="button" id="language_close_{$lang_index}" {if $language_more|@count lt 2} style="display:none"{/if}>&times;</button>
												<div class="span5">
													<select class="span12 margintop" name="language_more[]">
														<option value="">Select a language</option>
														{html_options  options=$ep_language_list selected=$lang}
													</select>
												</div>
												<div class="skillstat span5 offset1">
													<div>
														<label for="slider-language_number_{$smarty.foreach.moreLanguage.index}" class="muted">Your level :</label>
														<input type="text" id="slider-language_number_{$smarty.foreach.moreLanguage.index}" value="{$percent}" name="lang_slider_more[]"/>
													</div>
													<div id="slider-language_{$smarty.foreach.moreLanguage.index}" class="lang_slider">{$percent}</div>
													<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Bilingual</span>
												</div>
										</div>
										<!-- end, new language row -->
								{/foreach}						
							
							{else}							
								<!-- Start, new language row --> 
								<div class="addmore" id="language_more_0">  
										<div class="span5">
											<select class="span12 margintop" name="language_more[]">
												<option value="">Select a language</option>
												{html_options  options=$ep_language_list}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-language_number_0" class="muted">Your level :</label>
												<input type="text" id="slider-language_number_0" name="lang_slider_more[]" value="50"/>
											</div>
											<div id="slider-language_0" class="lang_slider">50</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Bilingual</span>
										</div>
								</div>
								<!-- end, new language row -->
							{/if}

								<!-- start, add language row button -->
									<p class="addmore-button" id="addmore_lang_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add a language</a></p>
								<!-- end, add language row button -->
							<!-- end, add language row -->
						</div>           
					</div> 
				</div>
			</div>

			<!-- End, Languages module --> 


			<!-- Start, Skills module -->    
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Skills &amp; level <span class="error">*</span></strong></label>

						<div class="controls span8" >
							{if $category_more|@count gt 0}
								{foreach from=$category_more key=kcategory item=percent name="moreSkills}
								{assign var=skill_index value=$smarty.foreach.moreSkills.index}
									<!-- Start, new skill row -->     
									<div class="addmore" id="skill_more_{$skill_index}">  
										<button  class="close" type="button" id="skill_close_{$skill_index}" {if $category_more|@count lt 2} style="display:none"{/if}>&times;</button>
										<div class="span5">
											<select class="required span12 margintop" name="ep_category[]" id="ep_category_{$smarty.foreach.moreSkills.index}">
												<option value="">Select a skill</option>
												{html_options  options=$ep_categories_list selected=$kcategory}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-skill_number_{$smarty.foreach.moreSkills.index}" class="muted">Your level</label>
												<input type="text" id="slider-skill_number_{$smarty.foreach.moreSkills.index}" value="{$percent}" name="category_slider_more[]"/>
											</div>
											<div id="slider-skill_{$smarty.foreach.moreSkills.index}" class="skill_slider">{$percent}</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Expert</span>
										</div>
									</div>
									<!-- end, new skill row -->
								{/foreach}
							{else}
									<!-- Start, new skill row -->     
									<div class="addmore" id="skill_more_0">  
										<div class="span5">
											<select class="span12 margintop" name="ep_category[]" id="ep_category_0">
												<option value="">Select a skill</option>
												{html_options  options=$ep_categories_list selected=$category}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-skill_number_0" class="muted">Your level :</label>
												<input type="text" id="slider-skill_number_0" name="category_slider_more[]" value="50"/>
											</div>
											<div id="slider-skill_0" class="skill_slider">50</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Expert</span>
										</div>
									</div>
									<!-- end, new skill row -->	
							{/if}		
								<!-- start, add language row button -->
									<p class="addmore-button" id="addmore_skill_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add a skill</a></p>
								<!-- end, add language row button -->
							<!-- end, new skill row -->
						</div>           
					</div> 
				</div>
				<!-- End, Skills module -->   
			</div> 

			<!-- Start, Job module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Work Experience <span class="error">*</span></strong>
							<br><span id="job_error"></span>
						</label>

						<div class="controls span8">
							{if $jobDetails|@count gt 0}
								{foreach from=$jobDetails item=job name="job_details"}
									{assign var=job_index value=$smarty.foreach.job_details.index+1}
									
									<!-- Start, job row -->
									<div class="addmore" id="job_more_{$job_index}">
										
										<button  class="close" type="button" id="job_close_{$job_index}" rel="{$job.identifier}"  {if $jobDetails|@count lt 2} style="display:none"{/if}>&times;</button>
										
										<label><input class="span5" id="JobName_{$job_index}" value="{$job.title}" name="job_title[]" placeholder="Job title"></label>
										<label><input class="span5" id="CompanyName_{$job_index}" value="{$job.institute}" name="job_institute[]" placeholder="Company name"></label>
										<select class="span5" name="ep_job[]" id="ep_job_{$job_index}">
											<option value="">Select contract type</option>
											<option value="cdi" {if $job.contract=='cdi'}selected{/if}>CDI</option>
											<option value="cdd" {if $job.contract=='cdd'}selected{/if}>CDD</option>
											<option value="freelance" {if $job.contract=='freelance'}selected{/if}>Freelance</option>
											<option value="intern" {if $job.contract=='intern'}selected{/if}>Interim</option>
											<option value="stage" {if $job.contract=='stage'}selected{/if}>Stage</option>
										</select>
										<div class="clearfix">
											<div class="container-field span5">
												<label>
													<span class="span3">Start date</span>
												</label>												
													<select class="input-small inline" name="start_month[]">
														<option value="1" {if $job.from_month=='1'}selected{/if}>January</option>
														<option value="2" {if $job.from_month=='2'}selected{/if}>February</option>
														<option value="3" {if $job.from_month=='3'}selected{/if}>March</option>
														<option value="4" {if $job.from_month=='4'}selected{/if}>April</option>
														<option value="5" {if $job.from_month=='5'}selected{/if}>May</option>
														<option value="6" {if $job.from_month=='6'}selected{/if}>June</option>
														<option value="7" {if $job.from_month=='7'}selected{/if}>July</option>
														<option value="8" {if $job.from_month=='8'}selected{/if}>August</option>
														<option value="9" {if $job.from_month=='9'}selected{/if}>September</option>
														<option value="10" {if $job.from_month=='10'}selected{/if}>October</option>
														<option value="11" {if $job.from_month=='11'}selected{/if}>November</option>
														<option value="12" {if $job.from_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="start_year_{$job_index}" placeholder="Year" value="{$job.from_year}" name="start_year[]">
												
												<div class="collapse {if $job.still_working !='yes'} in {/if}" id="stillWorkingThere_{$job_index}">
													<label> 
														<span class="span3">End date</span>
													</label>
														<select class="input-small inline" name="end_month[]">
															<option value="1" {if $job.to_month=='1'}selected{/if}>January</option>
															<option value="2" {if $job.to_month=='2'}selected{/if}>February</option>
															<option value="3" {if $job.to_month=='3'}selected{/if}>March</option>
															<option value="4" {if $job.to_month=='4'}selected{/if}>April</option>
															<option value="5" {if $job.to_month=='5'}selected{/if}>May</option>
															<option value="6" {if $job.to_month=='6'}selected{/if}>June</option>
															<option value="7" {if $job.to_month=='7'}selected{/if}>July</option>
															<option value="8" {if $job.to_month=='8'}selected{/if}>August</option>
															<option value="9" {if $job.to_month=='9'}selected{/if}>September</option>
															<option value="10" {if $job.to_month=='10'}selected{/if}>October</option>
															<option value="11" {if $job.to_month=='11'}selected{/if}>November</option>
															<option value="12" {if $job.to_month=='12'}selected{/if}>December</option>
														</select>
														&nbsp;&nbsp;<input class="input-small inline" id="end_year_{$job_index}" placeholder="Year" value="{$job.to_year}" name="end_year[]">
																										
												</div>
												<label class="checkbox">
													<input type="checkbox" id="still_working_{$job_index}" data-target="#stillWorkingThere_1" data-toggle="collapse" {if $job.still_working =='yes'} checked {/if}  name="still_working[]">I still work here
												</label>
												<input type="hidden" name="job_identifier[]" value="{$job.identifier}">
											</div>
										</div> 
									</div>
									<!-- end, job row -->
								{/foreach}
							{else}		
								<!-- Start, job row -->
								<div class="addmore" id="job_more_1">
									<label><input class="span5" id="JobName_1" name="job_title[]" placeholder="Job title"></label>
									<label><input class="span5" id="CompanyName_1" name="job_institute[]" placeholder="Company name"></label>
									<select class="span5" name="ep_job[]" id="ep_job_1">
										<option value="">Select contract type</option>
										<option value="cdi">CDI</option>
										<option value="cdd">CDD</option>
										<option value="freelance">Freelance</option>
										<option value="intern">Interim</option>
										<option value="stage">Stage</option>
									</select>
									<div class="clearfix">
										<div class="container-field span5">
											<label>
												<span class="span3">Start date</span> 
											</label>	
												<select class="input-small inline" name="start_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="start_year_1" placeholder="Year" name="start_year[]">
											
											<div class="collapse in" id="stillWorkingThere_1">
												<label> 
													<span class="span3">End date</span> 
												</label>	
													<select class="input-small inline" name="end_month[]">
														<option value="1" selected>January</option>
														<option value="2">February</option>
														<option value="3">March</option>
														<option value="4">April</option>
														<option value="5">May</option>
														<option value="6">June</option>
														<option value="7">July</option>
														<option value="8">August</option>
														<option value="9">September</option>
														<option value="10">October</option>
														<option value="11">November</option>
														<option value="12">December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="end_year_1" placeholder="Year" name="end_year[]">
												
											</div>
											<label class="checkbox">
												<input type="checkbox" id="still_working_1" data-target="#stillWorkingThere_1" data-toggle="collapse" name="still_working[]">I still work here
											</label>
										</div>
									</div> 
								</div>
								<!-- end, job row -->
							{/if}	
							<p class="addmore-button" id="addmore_job_link"><a class="btn btn-link btn-small"><i class="icon-plus"></i> Add an experience</a></p>  
						</div>
					</div>
				</div>
			</div>  
			<!-- End, Job -->
			<!-- Start, Training module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Training/Education <span class="error">*</span></strong>
							<br><span id="edu_error"></span>
						</label>
						<div class="controls span8">
							{if $educationDetails|@count gt 0}
								{foreach from=$educationDetails item=education name="edu_details"}
									{assign var=edu_index value=$smarty.foreach.edu_details.index+1}
									<!-- Start, School row -->
									<div class="addmore" id="training_more_{$edu_index}">
										 	
											<button  class="close" type="button" id="training_close_{$edu_index}" rel="{$education.identifier}" {if  $educationDetails|@count lt 2} style="display:none"{/if}>&times;</button>
											
										<label><input class="span5" id="trainingName_{$edu_index}" value="{$education.title}" name="training_title[]" placeholder="Title of training/education"></label>
										<label><input class="span5" id="trainingSchoolName_{$edu_index}" value="{$education.institute}" name="training_institute[]" placeholder="School, University, etc..."></label>
										<div class="clearfix">  
											<div class="container-field span5">
												<label>
													<span class="span3">Start date</span> 
												</label>	
													<select class="input-small inline" name="start_train_month[]">
														<option value="1" {if $education.from_month=='1'}selected{/if}>January</option>
														<option value="2" {if $education.from_month=='2'}selected{/if}>February</option>
														<option value="3" {if $education.from_month=='3'}selected{/if}>March</option>
														<option value="4" {if $education.from_month=='4'}selected{/if}>April</option>
														<option value="5" {if $education.from_month=='5'}selected{/if}>May</option>
														<option value="6" {if $education.from_month=='6'}selected{/if}>June</option>
														<option value="7" {if $education.from_month=='7'}selected{/if}>July</option>
														<option value="8" {if $education.from_month=='8'}selected{/if}>August</option>
														<option value="9" {if $education.from_month=='9'}selected{/if}>September</option>
														<option value="10" {if $education.from_month=='10'}selected{/if}>October</option>
														<option value="11" {if $education.from_month=='11'}selected{/if}>November</option>
														<option value="12" {if $education.from_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" placeholder="Year" id="start_train_year_{$edu_index}" value="{$education.from_year}" name="start_train_year[]">
												
												<div class="collapse  {if $education.still_working !='yes'} in {/if}" id="stillTrainingThere_{$edu_index}">
													<label>
														<span class="span3">End date</span> 
													</label>	
														<select class="input-small inline" name="end_train_month[]">
														<option value="1" {if $education.to_month=='1'}selected{/if}>January</option>
														<option value="2" {if $education.to_month=='2'}selected{/if}>February</option>
														<option value="3" {if $education.to_month=='3'}selected{/if}>March</option>
														<option value="4" {if $education.to_month=='4'}selected{/if}>April</option>
														<option value="5" {if $education.to_month=='5'}selected{/if}>May</option>
														<option value="6" {if $education.to_month=='6'}selected{/if}>June</option>
														<option value="7" {if $education.to_month=='7'}selected{/if}>July</option>
														<option value="8" {if $education.to_month=='8'}selected{/if}>August</option>
														<option value="9" {if $education.to_month=='9'}selected{/if}>September</option>
														<option value="10" {if $education.to_month=='10'}selected{/if}>October</option>
														<option value="11" {if $education.to_month=='11'}selected{/if}>November</option>
														<option value="12" {if $education.to_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="end_train_year_{$edu_index}" placeholder="Year" value="{$education.to_year}" name="end_train_year[]" >
													
												</div>
												<label class="checkbox">
													<input type="checkbox" id="still_training_{$edu_index}" data-target="#stillTrainingThere_{$edu_index}" name="still_training[]" data-toggle="collapse" {if $education.still_working =='yes'} checked {/if}>I am still in training/education
												</label>
												<input type="hidden" name="training_identifier[]" value="{$education.identifier}">
											</div>
										</div> 
									</div>
									<!-- end, school row -->	
									
								{/foreach}
							{else}	
								<!-- Start, School row -->
								<div class="addmore" id="training_more_1">
									<label><input class="span5" id="trainingName_1" name="training_title[]" placeholder="Title of training/education"></label>
									<label><input class="span5" id="trainingSchoolName_1" name="training_institute[]" placeholder="School, University, etc..."></label>
									<div class="clearfix">  
										<div class="container-field span5">
											<label>
												<span class="span3">Start date</span> 
											</label>	
												<select class="input-small inline" name="start_train_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="start_train_year_1" placeholder="Year" name="start_train_year[]">
											
											<div class="collapse in" id="stillTrainingThere_1">
												<label>
													<span class="span3">End date</span> 
												</label>	
													<select class="input-small inline" name="end_train_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="end_train_year_1" placeholder="Year" name="end_train_year[]">
												</label>
											</div>
											<label class="checkbox">
												<input type="checkbox" id="still_training_1" data-target="#stillTrainingThere_1" name="still_training[]" data-toggle="collapse">I am still in training/education
											</label>
										</div>
									</div> 
								</div>
								<!-- end, school row -->
							{/if}	
							<p class="addmore-button" id="addmore_training_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add training/education</a></p>  
						</div>
					</div>
				</div>
			</div>  
			<!-- End, Training module -->
			<!-- Start, personal info module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Personal information <span class="error">*</span></strong></label>    
						<div class="controls span8">
							<label>
								<select class="span5" name="nationality" id="nationality">
									<option value="">Nationality</option>
									{html_options  options=$ep_nationality_list selected=$nationality}									
								</select>
							</label>
							<label><input class="span5" id="address" name="address" placeholder="Address" value="{$address}"></label>
							<label><input class="span5" id="phone_number" name="phone_number" placeholder="Phone" value="{$phonenumber}"></label>
							<label><input class="span5" id="city" name="city" placeholder="City" value="{$city}"></label>
							<label><input class="span5" id="zipcode" name="zipcode" placeholder="Postcode" value="{$postcode}"></label>

							<label>
								<select class="span5" name="country" id="country">
									<option value="">Pays</option>
									{html_options  options=$ep_pays_list selected=$country}
								</select>
							</label>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, personal info module -->

			<!-- Start, billing info module -->
			<div class="mod" id="pay_info_type">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Invoicing information {if $smarty.get.profile eq 'invoice'}<span class="error">*</span>{/if}</strong> <span class="help-block">This information can be added when editing the first invoice</span></label>    
						<div class="controls span8">
							<label class="radio">
								<input type="radio" name="payinfo" value="ssn" {if $pay_info_type=='ssn'} checked class="collapsed" {/if} data-target="#national-InsuranceNum" data-toggle="collapse">Droit d'auteur (AGESSA). 
							</label>
							<!-- if AGESSA is true, display the input "National Insurance number" -->
							<div id="national-InsuranceNum" {if $pay_info_type=='ssn'} class="collapse in out" {else} class="collapse out" {/if}>
								<i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="Social security number" name="ssn" id="ssn" value="{$SSN}">
							</div>

							<label class="radio">
								<input type="radio" name="payinfo" value="comp_num" {if $pay_info_type=='comp_num'} checked class="collapsed" {/if} data-target="#siretNum" data-toggle="collapse">Autoentrepreneur
							</label>
							<!-- if Autoentrepreneur is true, display the input "SIRET number" -->
							<div id="siretNum" {if $pay_info_type=='comp_num'} class="collapse in out" {else} class="collapse out" {/if}>
								<i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="Votre n&deg; de Siret pour les factures" name="company_number" id="company_number" value="{$company_number}">
								<label class="checkbox"><input type="checkbox"  name="vat_check" data-target="#TVANum" data-toggle="collapse" value="YES" id="vat_check" {if $vat_check=='YES' } checked {/if}>Please tick this box if you pay VAT</label>
								<div id="TVANum" {if $vat_check=='YES'} class="collapse in out" {else} class="collapse out" {/if}>
									<i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="VAT" name="VAT_number" id="VAT_number" value="{if $vat_check=='YES'}{$VAT_number}{/if}" >
								</div>	
							</div>						
							<label class="radio">
								<input type="radio" name="payinfo" value="out_uk" {if $pay_info_type=='out_uk'} checked {/if}>Outside of UK
								<div class="help-block">For this status, a foreign postal address will suffice. Please ensure it is correct. Please select the bank transfer payment method. You will take on the costs of bank charges. </div>
							</label>
							<br>
							<span id="payinfo_error"></span>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, billing info module -->
			<!-- Start, payment info module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Preferred payment method {if $smarty.get.profile eq 'invoice'}<span class="error">*</span>{/if} </strong></label>    
						<div class="controls span8">
							<label class="radio">
								<input type="radio" type="radio" value="paypal" {if $payment_type == 'paypal'}checked class="collapsed"{/if} name="payment_type" data-target="#paypalEMayl" data-toggle="collapse">Paypal
							</label>
							<!-- if Payapl is true, display the input "paypal eMayl" -->
							<div id="paypalEMayl" {if $payment_type=='paypal'} class="collapse in out" {else} class="collapse out" {/if} >
								<i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="paypal eMayl" name="paypal_id" id="paypal_id" value="{$paypal_id}">
							</div>
							<label class="radio" id="cheque_radio" {if $pay_info_type=='out_uk' || $country!=101} style="display:none" {/if}>
								<input type="radio" value="cheque" {if $payment_type == 'cheque'}checked{/if} name="payment_type">Cheque
							</label>
							<label class="radio">
								<input type="radio" value="virement" {if $payment_type == 'virement'}checked{/if} name="payment_type">Bank transfer
							</label>
							<!-- if virement is true, display the input "paypal eMayl" -->
							<div id="virementId" {if $payment_type=='virement'} class="collapse in out" {else} class="collapse in" {/if} >								
								<div id="c_france" {if $pay_info_type!='out_uk' && $payment_type == 'virement' && $country==101 }style="display:block"{else}style="display:none"{/if}>
									<i class="icon-arrow-right"></i> 
									<input type="text" value="{$rib_id_1}" class="span3" placeholder="Nom de l'&eacute;tablissemen" name="rib_id_1" id="rib_id_1"/>
									<input type="text" value="{$rib_id_2}" class="span2" placeholder="Code Banque" name="rib_id_2" id="rib_id_2"/>
									<input type="text" value="{$rib_id_3}" class="span2" placeholder="Code Guichet" name="rib_id_3" id="rib_id_3"/>
									<input type="text" value="{$rib_id_4}" class="span3" placeholder="Num&eacute;ro de compte" name="rib_id_4" id="rib_id_4"/>
									<input type="text" value="{$rib_id_5}" class="span1" placeholder="Cl&eacute; RIB" name="rib_id_5"  id="rib_id_5"/>
								</div>	
								<div id="c_out_uk" {if ($pay_info_type=='out_uk' && $payment_type == 'virement') || $country!=101 }style="display:block"{else}style="display:none"{/if}>
									<i class="icon-arrow-right"></i>
									<input type="text" value="{$rib_id_6}" class="span3" placeholder="BIC" name="rib_id_6" id="rib_id_6"/>
									<input type="text" value="{$rib_id_7}" class="span2" placeholder="IBAN" name="rib_id_7" id="rib_id_7"/>									
								</div>
							</div>
							<br>
							<span id="payment_error"></span>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, payment info module -->

			<div class="mod">
				<div class="pull-right">
					<button class="btn inline" id="cancel">Cancel</button> 
					<button class="btn btn-primary inline"><i class="icon-refresh icon-white"></i> Save</button>
				</div>
			</div>
		</form>
	</section>
</div>
