<div class="container">
 
	<!-- start, status -->
	<div class="row-fluid">
		<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">×</button>
			<i class="icon-ok icon-white"></i> Congratulations! The commitment contract has been confirmed between you and Edit-place.
		</div>   
		<div class="span12" id="state2">
			<ul class="unstyled">
			<li data-original-title="I am quoting a rate for each selected offer" rel="tooltip" class="span4"><span class="bid-selection">My selected offers</span></li>
			<li data-original-title="Signature of Edit-place contract" rel="tooltip" class="span4"><span class="contract">Edit-place contract</span></li>
			<li data-original-title="My quotes can now be seen by Edit-place and its clients" rel="tooltip" class="hightlight span4"><span class="participant-ok">Validation</span></li>
			</ul>
		</div>
	</div>
	 
	 <!-- end, status -->
 
	<h1>Your participation has been confirmed</h1>
   
  
	<div class="mod">
		<div class="row-fluid">
			<div class="span5 alert">
				<h5><i class="icon-warning-sign"></i> <strong>You cannot start writing/proofreading your articles immediately.</strong></h5>
				<p><b> Premium mission/proofreading :</b> Edit-place will select your application within an hour and will inform you via email whether you can start writing/proofreading this article. </p>
				<p><b>Freedom mission :</b> the client can :
				<ol>
				  <li>Select a writer. Edit-place cannot guarantee the response timeline of the client.</li>
				  <li>No writer to be selected. In this case, your application will be accounted for in your maximum number of participations allowed until your offer expires.</li>
				</ol>
				</p>
				<p>
				<b>Premium quote :</b> Edit-place will notify you by email if the quote becomes a premium Mission
				</p>
				<div class="pull-right"><a href="/contrib/ongoing" class="btn">Return to My Contributions</a></div>
			</div>
			<div class="span5 offset1">
				<div style="padding: 20px 0" class="pull-center"><img src="/FO/images/user-x.png"></div>
				<h5><strong>Increase your chances of being selected by completing or updating your profile!</strong></h5>
				<p>Edit-place and the clients will pay close attention to your profile when selecting</p>
				<div class="pull-center"><a href="/contrib/modify-profile" class="btn btn-primary"><i class="icon-refresh icon-white"></i> Update my profile</a></div>
			</div>
		</div>
	</div>
</div>