{literal}
<script type="text/javascript">
// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	startTimer('time1','text1'); //timer ids starting with
	startTimer('time2','text2');//timer ids starting with
</script>
{/literal}
{if $pollDetails | @count gt 0}
	{foreach from=$pollDetails item=poll name=details}
	<section id="a_o">
		
			{if $mission_type eq 'poll_premium'}
				<div class="dp">
				<span data-placement="right" rel="tooltip" data-original-title="This offer may become a Premium mission" class="label label-quote-premium">Premium quote</span>
			{elseif $mission_type eq 'poll_nopremium'}
				<div class="dl">
				<span data-placement="right" rel="tooltip" data-original-title="Vous travaillerez en direct avec le client" class="label label-quote">Devis  Libert&eacute;</span>	
			{/if}			
			<h2>{$poll.title}</h2>

			<div class="summary clearfix">
					<ul class="unstyled">
						<li><strong>Call to writers</strong> <span class="bullet">&#9679;</span></li>
						<li> Language : <img class="flag flag-{$poll.language}" src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$poll.language_name}"> <span class="bullet">&#9679;</span></li>
						<li>Category : {$poll.category} <span class="bullet">&#9679;</span></li>
						<li>Nb. of words : {$poll.min_sign} - {$poll.max_sign} / article<span class="bullet">&#9679;</span></li>
						<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentCount}</a></li>
						{if $poll.spec_exists eq 'yes'}
							<li class="pull-right"><a href="/contrib/download-file?type=pollbrief&article_id={$poll.pollId}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> Download the client brief</a></li>
						{/if}	
					</ul>
				</div>

			<div class="a_o-details">
				<!-- start, colonne generale -->
				<div class="row-fluid">
					<div class="span7">
					<!-- start, colonne stat -->
						<div class="row-fluid stat-block">
							<div class="span4 section">Time remaining
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
									{else}
										<span id="time1_{$poll.pollId}_{$poll.timestamp}">
											<span id="text1_{$poll.pollId}_{$poll.timestamp}">{$poll.timestamp}</span>
										</span>
									{/if}	
								</p>
								</div>
								<div class="span4 section">
								<span rel="popover" data-placement="top" data-html="true" data-content="* Estimated time if the quote becomes Premium mission" data-trigger="hover">
									Production time
									<p>
										{if $upcoming eq 'yes'}
											&#9679;&#9679;&#9679;
										{else}
											<em>{$poll.production_time}</em> h
										{/if}	
									</p>
								</span>
								</div>
							<div class="span4 section">Client<p><img src="{$poll.client_pic}"  class="logo"/></p></div>
						</div>
						<div class="row-fluid note">
							<div class="span12">
								{if $mission_type eq 'poll_premium'}
									<p><i class="icon-info-sign icon-white"></i> Respond to this quote and become a <strong> priority candidate for 24h</strong> if the offer turns into a <span class="label label-premium">premium mission</span></p>
								{elseif $mission_type eq 'poll_nopremium'}
									<p><i class="icon-info-sign icon-white"></i> <strong>Try your luck! Please note that this may be a simple information-gathering exercise or a full writing mission.</p>
								{/if}
							</div>

						</div>
					<!-- end, colonne stat -->
					</div>

					<div class="span5">
						<table class="table">
							{if $upcoming eq 'yes'}
								<tr><td class="title">Open offer</td><td class="countdown">{$poll.publishtime_format}</td></tr>
								<tr>
									<td colspan="2" class="cta" >
										<span id="alert_{$poll.pollId}">											
											{if $poll.alert_subscribe eq 'no'}
												<button class="btn" onclick="subscribeAOAlert('{$poll.pollId}','yes','poll');"><i class="icon-bell"></i> Receive an alert</button>
											{elseif $poll.alert_subscribe eq 'yes'}
												<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$poll.pollId}','no','poll');"><i class="icon-remove icon-white"></i> Alert set</a>
											{/if}
										</span>
										
									</td>
								</tr>
							{else}
								<tr><td class="title">Contributors</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Contributor information" data-placement="left" data-html="true" {if $poll.participants_pic} data-content="{$poll.participants_pic}" data-trigger="hover"{/if}>{$poll.totalParticipation}</a></em></td></tr>
								<tr><td class="title">Last rate offered</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="All offered rates" data-placement="left" data-html="true" {if $poll.participants_price} data-content="{$poll.participants_price}" data-trigger="hover"{/if}>
								{if $poll.latestPrice} 
									{$poll.latestPrice} 
									{if $poll.currency eq 'euro'	}
										&euro;
									{else}
										&pound;
									{/if}
								{else}
									NA
								{/if}
								
								</a></em></td></tr>
								{if !$request_from && $ResponseExist eq 'yes'}
								<tr><td colspan="2" class="cta" id="tender_select_{$poll.pollId}">								
									{if $poll.display eq 'no' || $disabled eq 'yes'}
										<button class="btn btn-large btn-primary disabled">Post added</button>	
									{elseif $poll.attended eq 'YES'}								
										<button  onClick="fnCartDevisModifiers('p_remove','{$poll.pollId}','');" class="btn btn-large btn-danger">Post added</button>
									{elseif $poll.attended eq 'NO'}
										<button onClick="fnCartDevisModifiers('p_add','{$poll.pollId}','');" class="btn btn-large btn-primary">Add to my selection</button>
									{/if}	
									</td></tr>
								{/if}
							{/if}	
						</table>
					</div>
				</div>
				<!-- end, colonne generale -->
				{if $upcoming neq 'yes'}
					<!-- Start, question form -->
						{include file="Contrib/popup_devis-q.phtml"}	
					<!-- Stop, question form -->				
				{/if}	
				
			</div>
			<!-- Start, comment form -->
			{include file="Contrib/article-comments.phtml"}
			<!-- Stop, comment form -->
			
		</div>
	</section>

	<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
	<div id = "confirmDiv"></div>
	{include file="Contrib/popup_confirm_selection.phtml"}
{/foreach}
{else}
<section>
	<div class="row-fluid">
		<div class="pull-center span10 offset1">
			<p class="text-error lead"> You cannot take part in this mission.</p>
		</div>
	</div>
</section>
{/if}	
{literal}
<script>
 	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
</script>	
{/literal}