{literal}
<script type="text/javascript">
// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	startTimer('time1','text1'); //timer ids starting with
	startTimer('time2','text2');//timer ids starting with
</script>
{/literal}
{if $correctionDetails | @count gt 0}
	{foreach from=$correctionDetails item=correction name=details}
	<section id="a_o">
		<div class="mc">
			{if $correction.missiontest eq 'yes'}
				<span class="label label-test-mission" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Test Mission</span>
			{else}
				<span class="label label-correction" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Mission</span>
			{/if}
			<h2>{$correction.title}</h2>

			<div class="summary clearfix">
				<ul class="unstyled">
					<li><strong>Proofreading</strong> <span class="bullet">&#9679;</span></li>
					<li> Language : <img class="flag flag-{$correction.language}" src="/FO/images/shim.gif"> <span class="bullet">&#9679;</span></li>
					<li>Category : {$correction.category} <span class="bullet">&#9679;</span></li>
					<li>Nb. of words : {$correction.num_min} - {$correction.num_max} / article<span class="bullet">&#9679;</span></li>
					<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentCount}</a></li>
					{if $correction.spec_exists eq 'yes'}
						<li class="pull-right"><a href="/contrib/download-file?type=correctionbrief&article_id={$correction.articleid}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> Download client's brief</a></li>
					{/if}	
				</ul>
			</div>

			<div class="a_o-details mod">
				<!-- start, colonne generale -->
				<div class="row-fluid">
					<div class="span7">
						<!-- start, colonne stat -->
						<div class="row-fluid stat-block">
							<div class="span4 section">Time remaining
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
									{else}
									<span id="time1_{$correction.articleid}_{$correction.timestamp}">
										<span id="text1_{$correction.articleid}_{$correction.timestamp}">{$correction.timestamp}</span>
									</span>
									{/if}		
								</p>
								</div>
								<div class="span4 section">Proofread time
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
									{else}
									{$correction.correction_submission_text}
									{/if}	
								</p>
								</div>
							<div class="span4 section">Client<p><img src="{$correction.client_pic}"  class="logo"/></p></div>
						</div>
						<div class="row-fluid note">
							<div class="span5">
								<p>
									<img src="{$correction.writer_pic}" class="pull-left photo">Author
									<div class="name">
										{if $correction.writer_name}
											{$correction.writer_name}
										{else}
											Inconnu
										{/if}	
									</div>
								</p>
							</div>
							<div class="span7">
								<p><i class="icon-arrow-left icon-white"></i> You will be proofreading this author's articles</p>
							</div>
						</div>
						<!-- end, colonne stat -->
					</div>

					<div class="span5">
						<table class="table table-hover">
						{if $upcoming eq 'yes'}
								<tr><td class="title">Price Range</td><td class="countdown"><em>{$correction.correction_pricemin|zero_cut:2} - {$correction.correction_pricemax|zero_cut:2} &euro;</em></td></tr>
								<tr><td class="title">Open offer</td><td class="countdown">{$correction.publishtime_format}</td></tr>
								<tr>
									<td colspan="2" class="cta" >
										<span id="alert_correction_{$correction.deliveryid}">											
											{if $correction.alert_subscribe eq 'no'}
												<button class="btn" onclick="subscribeAOAlert('{$correction.deliveryid}','yes','article-correction');"><i class="icon-bell"></i>Receive an alert</button>
											{elseif $correction.alert_subscribe eq 'yes'}
												<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$correction.deliveryid}','no','article-correction');"><i class="icon-remove icon-white"></i>  Alert set</a>
											{/if}
										</span>
										
									</td>
								</tr>
						{else}
							<tr>
								<td class="title">Contributors</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Contributor information" data-placement="left" data-html="true"  {if $correction.participants_pic} data-content="{$correction.participants_pic}" data-trigger="hover"{/if}>{$correction.participants}</a></em></td>
							</tr>
							<tr>
								<td class="title">Price Range</td><td class="countdown">
									<em>{$correction.correction_pricemin|zero_cut:2} - {$correction.correction_pricemax|zero_cut:2} 
									{if $correction.currency eq 'euro'	}
										&euro;
									{else}
										&pound;
									{/if}
									</em>
								</td>
							</tr>
							<tr>
								<td class="title">Last rate offered</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="All offered rates" data-placement="left" data-html="true"  {if $correction.participants_price} data-content="{$correction.participants_price}" data-trigger="hover"{/if}>{$correction.latestPrice} 
								{if $correction.currency eq 'euro'	}
									&euro;
								{else}
									&pound;
								{/if}
								</a></em></td>
							</tr>
							{if !$request_from}
							<tr>
								<td colspan="2" class="cta" id="tender_select_{$correction.articleid}">
								{if $correction.display eq 'no' || $disabled eq 'yes'}
									<button class="btn btn-large btn-primary disabled">Post added</button>	
								{elseif $correction.attended eq 'YES'}								
									<button  onClick="fnCartCorrectionModifiers('c_remove','{$correction.articleid}','','{$correction.deliveryid}');" data-loading-text="Processing addition" class="btn btn-large btn-danger">Post added</button>
								{elseif $correction.attended eq 'NO'}
									<button  onClick="fnCartCorrectionModifiers('c_add','{$correction.articleid}','','{$correction.deliveryid}');" data-loading-text="Processing addition" class="btn btn-large btn-primary">Add to my selection</button>
								{/if}									
								</td>
							</tr>
							{/if}
						{/if}	
						</table>
					</div>
				</div>
				<!-- end, colonne generale -->
			</div>
			{include file="Contrib/article-comments.phtml"}	
		</div>
	</section>
	
	<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
	<div id = "confirmDiv"></div>
	{include file="Contrib/popup_confirm_selection.phtml"}
	{/foreach}
{/if}	

{literal}
<script>
 	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
</script>	
{/literal}