{literal}
<script type="text/javascript">
	$("#menu_royalties").addClass("active");
	
	var unpaidEuroCount={/literal}{$unpaidEuroCount}{literal};
	var unpaidPoundCount={/literal}{$unpaidPoundCount}{literal};

	/*function to check whether payment info added or not in profile
	if not then redirect to profile page to validate payment info
	if yes will show pop up with article details */
	
/* $(function(){	
	$("#invoicedetails").click(function(){
		
		$.get('/contrib/check-payment-info', function(data) {
			if(data=='YES')
			{
				$("#billing-ajax").modal({
					remote: "/contrib/invoicedetails"
				});
			}
			else
			{
				window.location.href='/contrib/modify-profile?profile=invoice#pay_info_type';
			}
			
		});			
	});
});	 */
function fninvoicedetails(currency)
{
	var unpaidCount=0;
	if(currency=='euro')
			unpaidCount=unpaidEuroCount;
	else if(currency=='pound')
			unpaidCount=unpaidPoundCount;	
		
	$.get('/contrib/check-payment-info', function(data) {
		if(data=='YES')
		{
			if(unpaidCount>0)
			{
				$("#confirmDiv").confirmModal({	
					heading: 'Confirm',
					body: "The missions that you are requesting payment for will be added to the purchase order that was already generated upon your first request this month.  The payment date that you are selecting for your second request will be considered for all the missions. Do you still wish to pursue this demand?",
					callback: function () {				
						$("#billing-ajax").modal({
							remote: "/contrib/invoicedetails?currency="+currency+"&oldinvoice=yes"
						});								
						//window.location="/contrib/generatepdf/";
					}	
				});
			}
			else{
				$("#billing-ajax").modal({
					remote: "/contrib/invoicedetails?currency="+currency
				});	
			}
			
		}
		else
		{
			window.location.href='/contrib/modify-profile?profile=invoice#pay_info_type';
		}
	});
}
	
</script>
{/literal}	

<div class="container">
	<!-- start, get contributor status -->
	<section id="status">
		<div class="row-fluid">
			<div class="profilehead-mod">
				<div class="span6">
					<h1>My royalties</h1>
				</div>

				<div class="span3 stat">
					<p>Awaiting payment</p>
					<p class="num-large"><a href="javascript:void(0);">
						{$pending_royalties[0].royalty|zero_cut:2} &{$pending_royalties[0].currency};
						{if $pending_royalties[0].royalty && $pending_royalties[1].royalty } , {/if}
						{if $pending_royalties[1].royalty}
								{$pending_royalties[1].royalty|zero_cut:2} &{$pending_royalties[1].currency};
						{/if}
						</a>
					</p>
				</div>
				<div class="span3 stat"><p>Total royalties</p><p class="num-large"><a href="#">
				{$total_royalties[0].royalty|zero_cut:2} &{$total_royalties[0].currency};
				{if $total_royalties[1].royalty}
						,{$total_royalties[1].royalty|zero_cut:2} &{$total_royalties[1].currency};
				{/if}				
				</a></p></div>
			</div>
		</div>
	</section>
	 <!-- end, contributor status --> 
    
	<section id="royalties-not-paid">
		<div class="row-fluid">
			<div class="mod">
				<div class="muted pull-right">Last updated {$smarty.now|date_format:"%d/%m/%Y"}</div>
				<h4>UNPAID COMPLETED MISSIONS <i class="icon icon-question-sign" rel="tooltip" data-original-title="One invoice is generated for all the work since last payment. The time to be paid (based on the type of request: advance / regular) starts when you request to be paid (min. {$ep_contrib_min_amount} euros or {$ep_contrib_min_amount} pounds)"></i> </h4>
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Date</th><th>Completed mission</th><th>Rate</th>
						</tr>
					</thead>
					{assign var=total value=0.0}
					{if $unpaidRoyalties|@count gt 0}		
						{foreach item=article from=$unpaidRoyalties name=invoice}
							<tr>
								<td>{$article.royalty_added_at|date_format:"%d/%m/%Y"}</td>
								<td><a href="/contrib/mission-published?article_id={$article.articleId}" target="_invoice">
								{$article.AOTitle} / {$article.client_name|capitalize} / {$article.article_created_date}
								</a></td>
								<td>{$article.price|zero_cut:2} 
								{if $article.currency eq 'euro'	}
									&euro;
								{else}
									&pound;
								{/if}
								</td>
							</tr>
						{assign var=total value=$total+$article.price}
						{/foreach}
						
					{else}
						
					{/if}					
				</table>
				{if $unpaidRoyalties|@count gt 0}
					<p class="alert" style="text-align: right"><strong>Total amount to pay : {if $unpaidEuroTotal} {$unpaidEuroTotal} &euro;{/if}
					{if $unpaidPoundTotal && $unpaidEuroTotal } , {/if}
					{if $unpaidPoundTotal} {$unpaidPoundTotal} &pound;{/if}
					</strong></p>
				{/if}					
				{if $unpaidEuroTotal >= $ep_contrib_min_amount || $unpaidPoundTotal >= $ep_contrib_min_amount }
					
						<p style="margin:-18px 0px 30px 0px;padding:8px 35px 8px 14px;">						
							{if $unpaidEuroTotal >= $ep_contrib_min_amount}
								<button class="btn btn-primary pull-right" id="invoicedetails" onclick="fninvoicedetails('euro')"; name="invoicedetails" type="button" style="margin-left:5px">Request payment(&euro;)</button>
							{/if}	
							{if $unpaidPoundTotal >= $ep_contrib_min_amount}
								  <button class="btn btn-primary pull-right" id="invoicedetails" onclick="fninvoicedetails('pound')"; name="invoicedetails" type="button">Request payment(&pound;)</button>
							{/if}
						</p>					
				{else}
					<p class="alert" style="text-align: right"><strong>You can ask for your payment from {$ep_contrib_min_amount} euros or {$ep_contrib_min_amount} pounds onwards.</strong></p>
				{/if}	
				
				<p class="alert" style="text-align: right"><strong>Payment is processed 15th of the following month post your request (fees range from 0% to 8% of the total amount paid).</strong></p>
			</div>
		</div>
	</section>
	<section id="billing-list">
		<div class="row-fluid">
			<div class="mod">
				<h4>MY INVOICES</h4>
				<table class="table table-hover">
					<thead>
						<tr><th>Invoice date</th><th>Invoice name</th><th>Total price</th><th>Status</th><th></th></tr>
					</thead>
					<tbody>
					{if $royalties | @count gt 0}	
						{foreach item=royalty from=$royalties}
						<!-- start, row -->
						<tr>
							<td>{$royalty.invoicedate|date_format:"%d/%m/%Y"}</td>
							<td>Edit-place invoice # {$royalty.invoiceId|replace:'ep_invoice_':''} - <a href="/contrib/invoicedetails?invoiceid={$royalty.invoiceId|replace:'ep_invoice_':''}" role="button" data-toggle="modal" data-target="#billing-ajax" class="muted">Details</a></td>
							<td>{$royalty.total_invoice_paid|zero_cut:2} &{$royalty.currency};</td>
							<td>
								{if $royalty.status=='refuse'}
									Refused
								{elseif $royalty.status=='Paid'}
									Paid
								{elseif $royalty.status=='inprocess'}
									In Process	
								{else}									
									{if $royalty.pay_later_month_name}									
										<span rel="tooltip" data-html="true" data-original-title="Payment to be received on the 15th of  {$royalty.pay_later_month_name}">
											Unpaid
										</span>	
									{else}
										Unpaid									
									{/if}
								{/if}
								
							</td>
							<td>
								{if $royalty.status=='Paid'}
									<a class="btn btn-small" href="/contrib/downloadinvoice?invoiceid={$royalty.invoiceId|replace:'ep_invoice_':''}"><i class="icon-file"></i> Download</a>			
								{/if}		
							</td>
						</tr>
						<!-- end, row -->
						{/foreach}

					{/if}	
					</tbody>
				</table>
				<!---Pagination start-->
					<div class="pagination pull-right">
						{include file="Contrib/pagination.phtml"}
					</div>	
					<!---Pagination END-->
			</div>
		</div>			
	</section>   
</div>
<div id = "confirmDiv"></div>
<!-- ajax use start -->
<div id="billing-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Invoice Details</h3>
	</div>
	<div class="modal-body">

	</div>
</div>
<!-- ajax use end -->