<!-- Block to display coming soon articles -->
<div class="mod">
	<h3 id="soon">Offers ended</h3>

	<table class="table table-hover">
		<thead>
			<tr>
				<th><a href="#orderByType">Type</a></th>
				<th>
					{if $smarty.get.torderByTitle eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=asc#finished">Title</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByTitle eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=desc#finished">Title</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByTitle=asc#finished">Title</a>	
					{/if}	
				</th>
				<th class="pc">
					{if $smarty.get.torderByLang eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=asc#finished">Languages</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByLang eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=desc#finished">Languages</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByLang=asc#finished">Languages</a>	
					{/if}								
				</th>
				<th class="pc">
					{if $smarty.get.torderByQuotePrice eq 'desc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByQuotePrice=asc#finished">Last quotes</a>
						<i class="icon-circle-arrow-down"></i>
					{elseif $smarty.get.torderByQuotePrice eq 'asc'}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByQuotePrice=desc#finished">Last quotes</a>
						<i class="icon-circle-arrow-up"></i>
					{else}
						<a href="/contrib/aosearch?search_article={$smarty.get.search_article|utf8_decode}&search_type={$smarty.get.search_type}&search_language={$smarty.get.search_language}&search_ao_type={$smarty.get.search_ao_type}&torderByQuotePrice=asc#finished">Last quotes</a>	
					{/if}
					
				</th>												
			</tr>
		</thead>
		{if $terminatedArticles |@count gt 0}
			{foreach item=article from=$terminatedArticles name="articledetails"} 								
				<tr>
					{if $article.ao_type eq 'correction'}
								<td>
								{if $article.missiontest eq 'yes'}
									<span class="label label-mission-test" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Test Mission</span>
								{else}
									<span class="label label-correction" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Proofreading Mission</span>
								{/if}
								{if $article.view_to eq 'sc'}
									<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?misson_type=correction&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}  {$article.picon} </span>
					{elseif $article.ao_type eq 'poll_premium'}
								<td><span class="label label-quote-premium" data-original-title="This offer may become a Premium mission" rel="tooltip" data-placement="right">Premium Quote</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=poll_premium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>
					{elseif $article.ao_type eq 'poll_nopremium'}
								<td><span class="label label-quote" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Freedom Quote</span>
								{if $article.contributors eq '0'}
									<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.contributors eq '1'}
										<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.contributors eq '3'}
										<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
								{/if}
								</td>
								<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=poll_nopremium&mission_identifier={$article.pollId}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes}</span>		
						{elseif $article.premium_option}
								<td>
								{if $article.missiontest eq 'yes'}
									<span class="label label-mission-test" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Test Mission</span>
								{else}
									<span class="label label-premium" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Premium Mission</span>
								{/if}
								{if $article.view_to eq 'sc'}
									<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
								{elseif $article.view_to eq 'jc'}
										<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
								{elseif $article.view_to eq 'jc0'}
										<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
								{/if}
							</td>
							<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=premium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
						{elseif !$article.premium_option}
						<td>
							{if $article.missiontest eq 'yes'}
								<span class="label label-mission-test" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Test Mission</span>
							{else}
								<span class="label label-quote" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Freedom Mission</span>
							{/if}
							{if $article.view_to eq 'sc'}
								<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>S</span>
							{elseif $article.view_to eq 'jc'}
								<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>J</span>
							{elseif $article.view_to eq 'jc0'}
								<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>B</span>	
							{/if}
						</td>
						<td class="title"><a class="muted"  href="/contrib/article-details?finished=yes&misson_type=nopremium&mission_identifier={$article.articleid}" role="button" data-toggle="modal" data-target="#viewOffer-ajax"><span {if $article.title|strlen gt 55} rel="tooltip" align="top" data-original-title="{$article.title|stripslashes}"{/if}>{$article.title|truncate:55:"...":true|stripslashes} {$article.picon} {$article.qicon}</span>
					{/if}									
					<p class="muted">{$article.category}  &bull;  Call to writers  &bull;  {$article.num_min} - {$article.num_max} words / article</p></a></td>
					<td class="pc"><img src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}" class="flag flag-{$article.language}"></td>
					<td class="countdown pc">
						<em>
						{if $article.latestPrice}
							{$article.latestPrice}
						{else}
							0 
						{/if}	
						{if $article.currency eq 'euro'	}
							&euro;
						{else}
							&pound;
						{/if}
						</em>
					</td>					
				</tr>								
			{/foreach}
		{else}
			<tr>
				<td colspan="6">
					<span class="no-data">No result</span>
				</td>
			</tr>
		{/if}
	</table>
</div>