<div class="modal-header">
	<button type="button" class="close" Onclick="dismissmodal();" aria-hidden="true">&times;</button>
	<div class="center-block">
		<h4>We have found similar quotes</h4>
		<p>These quotes are examples. You'll receive soon your personalized quote.</p>
	</div>
</div>

	<div class="center-block quote-pricing"> 
		<div class="table-responsive">  
			<table class="table table-bordered table-striped">
				<tbody>
				<tr><th></th><th>Tariff 1</th><th>Tariff 2</th><th>Tariff 3</th></tr>
				{foreach from=$pricestats item=price}
				<tr>
					<td><img width="50" height="50" src="/FO/images/imageB3/ctype-{$price.type}.png" alt="Guides"><div class="title">{if $contype=="writing"}Writing{else}Translation{/if} of {$type_array[$price.type]}<br> in {$lang_array[$language]}</div></td>
						<td><div class="price">{$price.price1} &pound;</div>Volume : {$price.num1}<br>Client's sector: {$category_array[$category]}</td>
					   <td><div class="price">{$price.price2} &pound;</div>Volume : {$price.num2}<br>Client's sector: {$category_array[$category]}</td>
						<td><div class="price">{$price.price3} &pound;</div>Volume : {$price.num3}<br>Client's sector: {$category_array[$category]}</td>
				</tr>
				{/foreach}
				</tbody>
			</table>  
		</div>
	</div>

<div class="modal-footer">
	<p class="center-block alert-info"><span class="glyphicon glyphicon-plus"></span> 
		{if $aotype=='premium'}
			A content strategist will contact you soon and propose a personnalized quote in less than 24 hours.
		{else}
			You are now going to precise your needs and display your ad on our platform.
		{/if}
	</p>    
	<button type="button" class="btn btn-default btn-lg" Onclick="dismissmodal();">Cancel</button>
	<button class="btn btn-primary btn-lg" onClick="document.quotes1form.submit();">Ok! Got it</button>
</div>

