{literal}
<script type="text/javascript" charset="utf-8" src="/FO/script/client/countdown.js"></script>
<script>
	$(document).ready(function(){
		//////////show timer article_submit_expires//////////
		
			$("#poll_time").countdown({
				timestamp	: $("#polltime").val(), 
				callback	: function(days, hours, minutes, seconds){

					var message = "";
					if(days!="0")
						hours=hours+(days*24);
						
					if(hours!="0")
						message += hours + "h" +"&nbsp;";
					if(minutes!="0")
						message += minutes + "mn";
					
					$("#poll_time").html(message);
					if(days==0 && hours==0 && minutes==0 && seconds==0)
					{
						$("#poll_time").html("Deadline expired");
						$("#addfav").show();
					}
				}
			});
	});
	var cur_date=$("#now").val();
	var js_date=(new Date().getTime())/ 1000;
	var diff_date=Math.floor(js_date-cur_date);
	
	function filterbyprice()
	{
		var Price=$("#filter_price").val().replace(",",".");
		if(Price=="")
		{	
			alert("Please insert a valid price");
			return false;
		}
		var id=$("#pollid").val();
		
		window.location="/client/devispremium?id="+id+"&filter="+Price;
		
	}
</script>
{/literal}

<br>
<div class="container">
	<section id="summary">
		<div class="row-fluid">
			<div class="span7">
				<h1>Premium quote <span>{$pollsdetail[0].title}</span></h1>
			</div>
			<div class="span2 stat">
				<p>Quotes received</p>
				<p class="num-large">{$pollsdetail[0].participationcount}</p>
			</div>
				<div class="span3 stat">
			<p>Receiving end in</p>
				<p class="num-large less24" id="poll_time"></p>   
			</div>
		</div>
	</section>
	
	<div class="row-fluid" id="favaddalert" style="display:none;">       
		<div class="alert alert-success">
			<button class="close" data-dismiss="alert" type="button">&times;</button>
			<i class="icon-ok icon-white"></i>
			Contributor (s) added (s) to your favorites!
		</div>
	</div>
	
	<div class="row-fluid">    
		<div class="span9">
		<input type="hidden" name="polltime" id="polltime" value="{$pollendtime}" />
			{if $pollsdetail[0].participationcount>0}
			<section id="sort-by">   
				<div class="filtering clearfix dp" style="padding-top: 5px; background: #f5f5f5">
					<div class="span4 title"><!--{$pollsetcount} tarifs propos&eacute;s : -->
						<span class="label label-warning" id="maxprice">{if $pollprice[0].maxprice!="0"}{$pollprice[0].maxprice|seventy_price:$pollprice[0].contrib_percentage|zero_cut:2}{else}{$pollprice[0].maxprice}{/if} {if $pollprice[0].currency=='pound'}&pound;{else}&euro;{/if} max</span> 
						<span class="label label-success" id="minprice">{if $pollprice[0].minprice!="0"}{$pollprice[0].minprice|seventy_price:$pollprice[0].contrib_percentage|zero_cut:2}{else}{$pollprice[0].minprice}{/if} {if $pollprice[0].currency=='pound'}&pound;{else}&euro;{/if} min</span> 
						{if $pollprice[0].participation>0}
							{math x=$pollprice[0].sumprice y=$pollprice[0].participation equation="(x/y)"  assign="average"}
						{/if}
						<span class="label label-reverse" id="avgprice">{if $pollprice[0].sumprice!="0"}{$average|seventy_price:$pollprice[0].contrib_percentage|zero_cut:2}{else}{$pollprice[0].sumprice}{/if} {if $pollprice[0].currency=='pound'}&pound;{else}&euro;{/if}moy.</span>
					</div>
					
					<div class="span3">   
						<div class="input-append" id="devispremiumtable_filter"> 
							<input class="span7" id="filter_price" name="filter_price" type="text" placeholder="Votre prix" aria-controls="devispremiumtable">
							<button class="btn btn-small" type="button"  style="height: 30px" onClick="filterbyprice();">Filter</button>
						</div>
					</div>
					
					<div class="span5">Sort by : 
						<a class="btn btn-link {if $smarty.get.sort=='dateasc' || $smarty.get.sort=='datedesc' }disabled{/if}" href="{$datesort_link}" style="cursor:pointer;">
							Date
							{if $smarty.get.sort=='dateasc'}
								<i class="icon-circle-arrow-up"></i>
							{elseif $smarty.get.sort=='datedesc'}
								<i class="icon-circle-arrow-down"></i>
							{/if}
						</a> 
						<a class="btn btn-link {if $smarty.get.sort=='priceasc' || $smarty.get.sort=='pricedesc'}disabled{/if}" href="{$pricesort_link}" style="cursor:pointer;">
							Prix
							{if $smarty.get.sort=='priceasc'}
								<i class="icon-circle-arrow-up"></i>
							{elseif $smarty.get.sort=='pricedesc'}
								<i class="icon-circle-arrow-down"></i>
							{/if}
						</a>
						<a class="btn btn-link" href="/client/devispremium?id={$smarty.get.id}">Default</a> 
					</div>
				</div>
			</section> 
			{/if}
			
			{if $pollset|@count gt 0}
			<section id="quote-listing-table">
				<div class="mod">   
					<form method="POST" name="pollform">
					
					<table class="table table-hover">
						<thead>
							<tr>
								<th><input type="checkbox" id="select_all" name="select_all" value="all" rel="tooltip" onclick="selectALL();" data-original-title="Select all"></th>
								<th>Photo</th>
								<th>Name of the writer</th>
								<th>Rate</th>
								<th style="text-align:center">Language</th>
								<th>Date of dispatch of quote</th>
								<th></th>
							</tr>
						</thead>
						
						{foreach from=$pollset item=poll name=pollloop}
							<tr>
								<td>
									{if in_array($poll.user_id,$favarray)}
										<input type="checkbox" name="contribtype[]" value="{$poll.id}#{$poll.user_id}" onClick="Addfavlist({$poll.user_id},'remove')" checked />
									{else}	
										<input type="checkbox" name="contribtype[]" value="{$poll.id}#{$poll.user_id}" onClick="Addfavlist({$poll.user_id},'add')" />
									{/if}
								</td>
								<td class="media">
									<a onclick="loaddevisprofile('{$poll.user_id}','{$poll.poll_id}','{$smarty.foreach.pollloop.index}');" class="pull-left imgframe" style="cursor:pointer;" role="button" data-toggle="modal" data-target="#viewDevisProfile-ajax">
										<img class="media-object" src="{$poll.profilepic}" width="60" height="60"/>
									</a>
								</td>
								<td class="title">
									<a onclick="loaddevisprofile('{$poll.user_id}','{$poll.poll_id}','{$smarty.foreach.pollloop.index}');" style="cursor:pointer;" role="button" data-toggle="modal" data-target="#viewDevisProfile-ajax">{$poll.name}</a>
									<div class="muted">{$poll.totalparticipation} participations<br>{$poll.selectedparticipation} selected times</div></td>
								<td class="price">{$poll.price_user|seventy_price:$poll.contrib_percentage|zero_cut:2} {if $pollprice[0].currency=='pound'}&pound;{else}&euro;{/if}</td>
								<td style="text-align:center">
									<img class="flag flag-{$poll.language}" src="/FO/images/shim.gif">
								</td>
								<td>{$poll.created_at}</td>
								<td id="partstatus_{$poll.id}">
									{if $poll.status=="active"}
										<a href="javascript:void(0);" onClick="pollparticipationactive({$poll.id},'{$poll.status}');" class="btn btn-small">Exclude</a>
									{elseif $poll.status=="inactive"}	
										<a href="javascript:void(0);" onClick="pollparticipationactive({$poll.id},'{$poll.status}');" class="btn btn-small">Include</a>
									{/if}
								</td> 
							</tr>
								
								
						{/foreach}
						{foreach from=$pollset1 item=poll1 }
							<input type="hidden" name="previous_{$poll1.user_id}" id="previous_{$poll1.user_id}" value="{$poll1.previous}" />
							<input type="hidden" name="next_{$poll1.user_id}" id="next_{$poll1.user_id}" value="{$poll1.next}" /> 
						{/foreach}
					</table>
					
					<hr> 
					
					<div class="btn-group">
						<button class="btn btn-small" type="submit" name="inactivate_all" id="inactivate_all" value="Exclude all" onClick="return updateParticipationall('inactive');">Exclude all</button>
						<button class="btn btn-small" type="submit" name="activate_all" id="activate_all" value="Include all" onClick="return updateParticipationall('active');">Include all</button>
						
						<a class="btn btn-small"  href="/client/downloadpollxls?id={$smarty.get.id}" style="margin-left:20px;">Export</a>
						<input type="hidden" id="pollid" name="pollid" value="{$smarty.get.id}" /> 
						<button class="btn btn-small" type="button" name="addfav" id="addfav" value="addfav" onClick="return addfavoritecontrib();" style="margin-left:20px;display:none;">Confirm selection</button>
					</div>
					</form>
					
				</div>    
			</section>
			<div class="span12">
					<!---Pagination start-->
						<div class="pagination pull-right">
							{include file="Client/pagination.phtml"}
						</div>	
					</div>
			{else}
				{if $smarty.get.filter!="" && $pollsdetail[0].participationcount>0}
					<h4>No quote for this price</h4>
				{else}
					<h4>You have not yet received a quote</h4>
				{/if}	
			{/if} 
			
			
			<section id="a_o" style="clear:both"> 
				<div class="mod">
					<div class="summary clearfix">
						<h4>DETAILS OF THE PROJECT</h4>
						<ul class="unstyled">
							<li><strong>Call to writen</strong> <span class="bullet">&bull;</span></li>
							<li> Language : <img src="/FO/images/shim.gif" class="flag flag-{$pollsdetail[0].language}"> <span class="bullet">&bull;</span></li>
							{assign var="cat" value=$pollsdetail[0].category}
							<li>Category : {$category_array.$cat} <span class="bullet">&bull;</span></li> 
							<li>Nb. of words : {$pollsdetail[0].min_sign}&nbsp;-&nbsp;{$pollsdetail[0].max_sign} </li>
							{if $pollsdetail[0].file_name!=""}
								<li class="pull-right">
									<a class="btn btn-small btn-success" href="/client/downloadpollbrief?id={$smarty.get.id}">
									<i class="icon-white icon-circle-arrow-down"></i> Download the client brief
									</a>
								</li>
							{/if}
						</ul>
					</div>
				</div>
			</section>
			
		</div>

		<div class="span3">
			<aside>
				<div class="aside-bg">
					{if $customerstrust|@count>0}
					<div id="we-trust" class="aside-block">
					   <h4>They trust them</h4>
					   <ul class="unstyled {if $customerstrust|@count>3}pre-scrollable{/if}">
							{foreach from=$customerstrust item=clogo key=ckey}  
								<li><img src="{$clogo}" rel="tooltip" data-original-title="{$ckey|utf8_decode}" data-placement="left"></li>
							{/foreach}
					   </ul>
					</div>
					{/if}
					
					<div id="quote-ongoing" class="aside-block">
						<h4>OTHER OFFERS</h4>
								<ul class="nav nav-tabs nav-stacked {if $quotes|@count>9}pre-scrollable{/if}">
							{if $quotes|@count>0}
								{foreach from=$quotes item=quote}
									<li>
										{if $quote.title|@strlen > 28}
											<a href="/client/quotes?id={$quote.id}" rel="tooltip" data-original-title="{$quote.title}" data-placement="left">
												{if $quote.valid=='yes'}
													<span class="badge pull-right badge-warning">1</span>
												{else}	
													<span class="badge pull-right">{$quote.participations}</span>
												{/if}
											{$quote.title|truncate:28:"...":true}
											</a>
										{else}
											<a href="/client/quotes?id={$quote.id}">	
												{if $quote.valid=='yes'}
													<span class="badge pull-right badge-warning">1</span>
												{else}	
													<span class="badge pull-right">{$quote.participations}</span>
												{/if}

											{$quote.title}</a>
										{/if}	
										
									</li>
								{/foreach}
							{else}
								<li><b>No Quotes</b></li>
							{/if}
						</ul>	
						<ul class="nav nav-tabs nav-stacked">
							<li><a href="/client/liberte1"><i class="icon-edit"></i> <strong>Ask for a new quote</strong></a></li>
						</ul>
					</div>
					
					<div class="aside-block" id="garantee">
						<h4>YOUR GUARANTEES</h4>

						<dl>
							<dt><span class="umbrella"></span>Edit-place is your mediator</dt>
							<dd>In the event of a dispute/issue (delay in delivery, article rewrites, refund…)</dd>
							<dt><span class="locked"></span>Secure payment</dt>
							<dd>Our online payment solution guarantees you a hassle-free transaction</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
</div>

<!-- ajax use start --> 
<div id="viewDevisProfile-ajax" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	{if $pollsetcount gt 1}
		<a class="lft" onclick="loaddevisprofile('{$poll.user_id}','{$smarty.get.id}','previous');" role="button" style="cursor:pointer;top:300px;">&lsaquo;</a>
		<a class="rgt" onclick="loaddevisprofile('{$poll.user_id}','{$smarty.get.id}','next');" role="button" style="cursor:pointer;top:300px;">&rsaquo;</a>  
	{/if}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Writer's profile</h3>
	</div>
	<div class="modal-body">
		<div id="profilecontent">
	
		</div>
	</div>
</div>
<!-- ajax use end -->