{literal}
<script language="javascript"> 
(function($,W,D)
	{
		var JQUERY4U = {};

		JQUERY4U.UTIL =
		{
			setupFormValidation: function()
			{
					//form validation rules
					$("#conactForm").validate({
						onkeyup:false,
						errorClass: 'error',
						validClass: 'valid',
						message:false,
						highlight: function(element) {
							$(element).closest('span').addClass("f_error");
						},
						unhighlight: function(element) {
							$(element).closest('span').removeClass("f_error");
						},
						rules: {
							contact_firstname:  {
								required: true
							},
							contact_lastname:  {
								required: true
							},
							contact_email:  {
								required: true,
								email: true
							},
							contact_phone: {
								required: true,
								number: true
							}
						}
					});
			    
			}
		}

		//when the dom has loaded setup form validation rules
		$(D).ready(function($) {
			JQUERY4U.UTIL.setupFormValidation();
		});

	})(jQuery, window, document);
</script>

<style>
		.error { display: none !important;}
		.f_error input, .f_error select, .f_error textarea {
			border-color: rgb(185, 74, 72);
			color: rgb(185, 74, 72);
		}
</style>
{/literal}	 
	
<section id="quote-selection">

	<div class="row-fluid">

		<!-- col 1 -->

		<div class="span8">

			<div class="profilehead-mod">

				<div class="span3">

					<div class="editor-container">

						<a class="imgframe-large" href="#">

							<img src="{$contribprofile[0].profilepic}" alt="{$contribprofile[0].first_name|ucfirst} {$contribprofile[0].last_name|ucfirst}">

						</a>

					</div>

				</div>

				<div class="span9 profile-name">

					<h3>{$contribprofile[0].name}</h3>

					<p class="" style="">{$contribprofile[0].age}  years old  <span class="muted">&bull;</span>  {$contribprofile[0].catstr}  <span class="muted">&bull;</span>  {$contribprofile[0].langstr}</p>

					<table class="table table-condensed table-hover">

						<tr>

							<td class="muted">{$contribprofile[0].participations} participations</td>

							<td class="muted">Selected {$contribprofile[0].selectedcount} times</td>

						</tr>

						<tr>

							<td class="muted">Clients : {$contribprofile[0].clientlist}</td>

							<td><a href="#skills">Profile details</a></td>

						</tr>

					</table>

				</div>

			</div>
			
			<div class="comment well well-large">
				<p><strong><i class="icon-comment"></i> About your offer : "{$contribprofile[0].title}"</strong></p>
				<p class="">
				</p>
			</div>

			<h3>Writer profile</h3>
			
			<section id="skills">
				<div class="mod">
					<h4>Languages</h4>
					{assign var="language" value=$contribprofile[0].language}
					<strong>{$language_array.$language}</strong> (mother tongue)
					{foreach from=$langpercent item=more key=lang}
						<div class="skillstat row-fluid">	
							<div class="span6">
								<p><strong>{$language_array.$lang}</strong>  {$more}%</p>
								<div class="progress">
									<div class="bar" style="width: {$more}%"></div>
								</div>
								<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Bilingual</span>
							</div>
						</div>
					{/foreach}	
				</div>

				<div class="mod">
					<h4>Skills/ Areas of expertise</h4>
					{foreach from=$contribprofile[0].cats item=cat}
						{if $catpercent.$cat!=""}
						<div class="skillstat row-fluid">
							<div class="span6">
								<p><strong data-original-title="Seo / marketing internet" rel="tooltip">{$category_array.$cat}</strong>  {$catpercent.$cat}%</p>
								<div class="progress">
								<div class="bar" style="width: {$catpercent.$cat}%"></div>
								</div>
								<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Expert</span>
							</div>
						</div>
						{/if}
					{/foreach}	
				</div>

				{if $exp_details|@count>0}
				<div class="mod">
					<h4>Work experience</h4>
					<dl>
						{foreach from=$exp_details item=exp}
							<dt>{$exp.title}</dt>
							<dd class="company">{$exp.institute}</dd>
							<dd class="muted">
								Contract type : {$exp.contract}
							</dd>
							<dd class="muted">
								<time> {$exp.from_month|ucfirst} {$exp.from_year}</time> - <time>{if $exp.to_year!="0"}{$exp.to_month|ucfirst} {$exp.to_year}{else}Current{/if}</time>
							</dd>
						{/foreach}
					</dl>
				</div>
				{/if}

				{if $education_details|@count>0}
				<div class="mod">
					<h4>Training/Education</h4>
					<dl>
						{foreach from=$education_details item=edu}
							<dt>{$edu.title}</dt>
							<dd class="company">{$edu.institute}</dd>
							<dd class="muted">
								<time> {$edu.from_month|ucfirst} {$edu.from_year}</time> - <time>{if $edu.to_year!="0"}{$edu.to_month|ucfirst} {$edu.to_year}{else}Current{/if}</time>
							</dd>
						{/foreach}
					</dl>
				</div>
				{/if}
			</section>
		</div>

		<!-- col 2 -->
		<div class="span4">
			<div class="quote-cta">
				<p class="quote-price">Total price :<strong> {$contribprofile[0].price_user_total|ceil} {if $contribprofile[0].currency=='pound'}&pound;{else}&euro;{/if}</strong><sup>*</sup></p>
				<ul class="unstyled stripe">
					{if $contribprofile[0].premium_option=="0"}
						<li>Writer tariff  : {$contribprofile[0].price_user|zero_cut:2} {if $contribprofile[0].currency=='pound'}&pound;{else}&euro;{/if}</li>
						<li>Edit-place fees included : {$contribprofile[0].ep_percent|zero_cut:2}%</li>
					{/if}
					{if ($contribprofile[0].valid_until!="no" && $contribprofile[0].premium_option!="0") || ($contribprofile[0].datevalid=="yes" && $contribprofile[0].premium_option=="0")}
					<li>*Guaranteed to Work {$contribprofile[0].valid_until}</li>
					{/if}
				</ul>
				
				{if $contribprofile[0].premium_option=="0" && $contribprofile[0].datevalid=="yes" && $contribprofile[0].cycle=="0" &&  $contribprofile[0].articlestatus!="closed_client"}
					<p><a  data-toggle="modal" href="#confirm-selection" class="btn btn-primary btn-block">Select this writer</a></p>
				{/if}
				{if $contribprofile[0].datevalid=="no" && $contribprofile[0].premium_option=="0"}
					<strong> *The date of validity of the license has expired</strong>
				{/if}
				
				{if $contribprofile[0].created_by=="FO"}
					<div class="private-info">
						<h4>Private quote</h4>
						<ul>
							<li>Assign only part of the mission to the writer </li>
							<li>Given a more important mission to writer </li>
						</ul>
						<p><a  data-toggle="modal" href="/client/quotes-1?article={$contribprofile[0].artid}&private={$contribprofile[0].user_id}" class="btn btn-primary btn-block"><span class="icon-lock icon-white"></span> Ask for a private quote</a></p>
					</div>
				{/if}				
				
		
				<aside>
					<div class="aside-bg">
						<div id="garantee" class="aside-block">
							<h4>YOUR GUARANTEES</h4>
							<dl>
								<dt><span class="umbrella"></span>Edit-place is your mediator</dt>
								<dd>In the event of a dispute/issue (delay in delivery, article rewrites, refund…)</dd>
								<dt><span class="locked"></span>Secure payment</dt>
								<dd>Our online payment solution guarantees you a hassle-free transaction</dd>
							</dl>
						</div>
						
						{if $contribprofile[0].clientlogo|@count>0}
						<div class="aside-block" id="we-trust">
							<h4>Publications</h4>
							<ul class="unstyled">
								{foreach from=$contribprofile[0].clientlogo item=clogo key=ckey}
									<li><img src="{$clogo}" rel="tooltip" data-original-title="{$ckey|utf8_decode}" data-placement="left"></li>
								{/foreach}
							</ul>
						</div>
						{/if}
					</div>
				</aside>	
			</div>
		</div>
	</div>
</section>


<a class="pull-right btn btn-small disabled anchor-top scroll" href="#brand"><i class="icon-arrow-up"></i></a>



<div id="confirm-selection" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<form method="POST" name="conactForm" id="conactForm" action="/client/order1?id={$contribprofile[0].id}">

		<div class="modal-header">

			<button type="button" class="close" onclick="$('#confirm-selection').hide();return false;" aria-hidden="true">&times;</button>

			<h3 id="myModalLabel">Confirm selection</h3>

		</div>

		<div class="modal-body">

			<p><strong>I want to confirm selecting {$contribprofile[0].name}. for my project "{$contribprofile[0].title} " costs {$contribprofile[0].price_user_total|ceil} {if $contribprofile[0].currency=='pound'}&pound;{else}&euro;{/if}</strong></p>

			<p>I receive an email confirmation via email and will be put in touch with {$contribprofile[0].name}.</p>
			
			<div class="mod form-horizontal">
				<div class="control-group">
					<label class="control-label" for="client-name"> First Name</label>
					<div class="controls">
						<span><input type="text" id="contact_firstname" name="contact_firstname" value="{$clientcontact[0].contact_firstname}" class="span3"></span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="client-surname"> Last Name</label>
					<div class="controls">
						<span><input type="text" id="contact_lastname" name="contact_lastname" value="{$clientcontact[0].contact_lastname}" class="span3"></span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="client-email"> Your email</label>
					<div class="controls">
						<span><input type="text" id="contact_email" name="contact_email" value="{$clientcontact[0].contact_email}" class="span3"></span>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="client-phone"> Telephone</label>
					<div class="controls">
						<span><input type="text" id="contact_phone" name="contact_phone" value="{$clientcontact[0].contact_phone}" class="span3"></span>
					</div>
				</div>
			</div>
		</div>

		<div class="modal-footer">

			<button class="btn" type="button" onclick="$('#confirm-selection').hide();return false;" aria-hidden="true">Cancel</button>

			<button class="btn btn-primary" type="submit">Confirm</button>

		</div>

		<input type="hidden" name="quote" id="quote" value="{$contribprofile[0].user_id}" />

		<input type="hidden" name="article" id="article" value="{$contribprofile[0].artid}" />

		<input type="hidden" name="contribprice" id="contribprice" value="{$contribprofile[0].price_user}" />

	</form>

</div>        



{literal}



<script>



	$("[rel=tooltip]").tooltip();

	$("[rel=popover]").popover();



</script>



{/literal}