<section class="quoteform" id="step3">
	<div class="container padding">
		<div class="center-block">
			<div class="alert alert-success">Thanks ! We have taken your request into account.</div>
			<h2>An account manager will contact you shortly</h2>
		</div>
		<div class="content-block quotelist">
			<h4>Your quote</h4>
			<div class="table-responsive">     
				<table class="table table-striped">
					<tr> 
						<th>Product</th>
						<th></th>
						<th>Volume</th>
						<th>Sector</th>
						<th>Languages</th>
						<th>Aim</th>
					</tr>
					{foreach from=$statarray item=quote}
					<tr>
						<td><img src="/FO/images/imageB3/ctype-{$quote.type}.png" width="50" height="50"></td>
						<td>{$quote.typetext}</td>
						<td>{if $quote.num==""}N/A{else}{$quote.num}{/if}</td>
						<td>{$category_array[$category]}</td>
						<td>{$lang_array[$quote.translation_from]},{$lang_array[$quote.translation_to]}</td>
						<td>{$quote.objectives}</td>
					</tr>
					{/foreach}
				</table>
			</div>
		</div>

		{if $categorywriters|@count gt 0}
		<div class="content-block recap-profile">
			<h4>Ex. of writers in the {$category_array[$category]} sector</h4>
			<ul style="margin-right:40px">
				{foreach from=$categorywriters item=contrib}
					<li>
						<span class="contrib-frame"><img src="/FO/profiles/contrib/pictures/{$contrib.user_id}/{$contrib.user_id}_h.jpg" class="media-object"></span>
						<div class="contrib-name clearfix">{$contrib.last_name}</div>
					</li>
				{/foreach}
			</ul>        
		</div>
		{/if}
		
			<div class="content-block quote-pricing">
			<div class="center-block">
				<h4>We have found similar Quotes</h4>
				<!--<p>Les tarifs sont indiqu&eacute;s &agrave; titre indicatif et sont des tarifs par <b><u>{$type_array[$type]|upper}</u></b>. Vous recevrez bientôt votre devis personnalisé</p>-->
				<p>These quotes are examples. You'll receive soon your personalized quote.</p>
				<div class="table-responsive">  
					<table class="table table-bordered table-striped">
						<tbody>
						<tr><th></th><th>Tariff 1</th><th>Tariff 2</th><th>Tariff 3</th></tr>
						{foreach from=$pricestats item=price}
						<tr>
							<td><img width="50" height="50" src="/FO/images/imageB3/ctype-{$price.type}.png" alt="Guides"><div class="title">{if $contype=="writing"}Writing{else}Translation{/if} of {$type_array[$price.type]}<br> in {$lang_array[$language]}</div></td>
								<td><div class="price">{$price.price1} &pound;</div>Volume : {$price.num1}<br>Client's sector: {$category_array[$category]}</td>
							   <td><div class="price">{$price.price2} &pound;</div>Volume : {$price.num2}<br>Client's sector: {$category_array[$category]}</td>
								<td><div class="price">{$price.price3} &pound;</div>Volume : {$price.num3}<br>Client's sector: {$category_array[$category]}</td>
						</tr>
						{/foreach}
						
					</tbody></table>  
				</div>
			</div>
		</div>
	</div>
</section>

<section class="dashit"  id="strategy-teasing">
	<div class="container padding">
		<div class="center-block">
			<h2>Edit-place expertise it is also...</h2>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-6 wow fadeInLeft">
				<h4>Editorial strategy</h4>
				<ul>
					<li>Selection of original subjects</li>
					<li>Dectecting best keywords to write on</li>
					<li>Proposal of new formats optimised for social networks</li>
					<li>Analyse and follow up of your results(ranking,shares)</li>
				</ul>
			</div> 
			<div class="col-xs-12 col-md-6 wow fadeInRight">
				<h4>Editorial Solutions</h4>
				<ul>
					<li>Integration of the content</li>
					<li>Content curation</li>
					<li>Community management</li>
					<li>Copywriting on existing content</li>
					<li>Press reviews</li>
				</ul>
			</div> 
		</div>   
	</div>
</section>


