<section class="quoteform" id="step3">
	<div class="container padding">
		<div class="center-block">
			<div class="alert alert-success">Thanks ! We have taken your request into account.</div>
			<p>Max. date for ad to be online : <span class="label label-warning" style="font-size:14px">{$time48}</span></p>
			<p>Your ad will be displayed to our writers specialized in :{$category_array[$category]}.</p>  
			<p>You'll receive a confirmation at this address : <em>{$client_email}</em>.</p>
		</div>
		<div class="content-block quotelist">     
			<h4><strong>Name of the project</strong> <br>
			{$missiontitle}</h4>      
			<div class="table-responsive">     
				<table class="table table-striped">
					<tr> 
						<th>Product</th>
						<th></th>
						<th>Volume</th>
						<th>Sector</th>
						<th>Languages</th>
						<th>Aim</th>
					</tr>
					{foreach from=$statarray item=quote}
					<tr>
						<td><img src="/FO/images/imageB3/ctype-{$quote.type}.png" width="50" height="50"></td>
						<td>{$quote.typetext}</td>
						<td>{if $quote.num==""}N/A{else}{$quote.num}{/if}</td>
						<td>{$category_array[$category]}</td>
						<td>{$lang_array[$quote.writing_lang]}</td>
						<td>{$quote.objectives}</td>
					</tr>
					{/foreach}
				</table>
			</div>
			<p><a href="/client/home?type=new" class="btn btn-default">More details</a></p> 
		</div>

		{if $categorywriters|@count gt 0}
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<div class="content-block recap-profile">
					<h4>Ex. of writers in the {$category_array[$category]} sector</h4>
					<ul style="padding-right:10px">
						{foreach from=$categorywriters item=contrib}
						<li>
							<span class="contrib-frame"><img src="/FO/profiles/contrib/pictures/{$contrib.user_id}/{$contrib.user_id}_h.jpg" class="media-object"></span>
							<div class="contrib-name clearfix">{$contrib.last_name}</div>
						</li>
						{/foreach}
					</ul>        
				</div>
			</div>
			<div class="col-xs-12 col-md-4">
				<div class="content-block">
					<h4><span class="glyphicon glyphicon-info-sign"></span> A propos des tarifs</h4>
					Edit-place prend une <strong>commission de 35%</strong> sur chaque mission réalisée par un rédacteur.
					Pensez à bien intégrer cette composante lorsque vous négociez votre tarif avec le rédacteur.
				</div>
			</div>
		</div>
		{/if}
	</div>  
</section>

<section class="dashit"  id="garantee">
	<div class="container padding">
		<div class="center-block">
			<h2>Edit-place guarantee</h2>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-4 col-md-offset-1 wow fadeInLeft">
				<div class="center-block"><img src="/FO/images/imageB3/mediateur.png" width="67" height="75" alt="Moderateur">
					<h4>Edit-place is your mediator</h4>
					<p>In the event of a dispute/issue (delay in delivery, article rewrites, refund...)</p>
				</div>
			</div> 
			<div class="col-xs-12 col-md-4 col-md-offset-2 wow fadeInRight">
				<div class="center-block">
					<img src="/FO/images/imageB3/secured.png" width="75" height="75" alt="Paiement sécurisé">
					<h4>Secure payment</h4>
					<p>Our online payment solution guarantees you a hassle-free transaction</p>
				</div> 
			</div>
		</div>   
	</div>
</section>

<section class="dashit"  id="strategy-teasing">
	<div class="container padding">
		<div class="center-block">
			<h2>Edit-place expertise it is also...</h2>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-6 wow fadeInLeft">
				<h4>Editorial strategy</h4>
				<ul>
					<li>Selection of original subjects</li>
					<li>Dectecting best keywords to write on</li>
					<li>Proposal of new formats optimised for social networks</li>
					<li>Analyse and follow up of your results(ranking,shares)</li>
				</ul>
			</div> 
			<div class="col-xs-12 col-md-6 wow fadeInRight">
				<h4>Editorial Solutions</h4>
				<ul>
					<li>Integration of the content</li>
					<li>Content curation</li>
					<li>Community management</li>
					<li>Copywriting on existing content</li>
					<li>Press reviews</li>
				</ul>
			</div> 
		</div>   
	</div>
</section>
