<!DOCTYPE html>
<html>
	<body>
		<input type="hidden" id="name" value="{$wrname}" />
		<input type="hidden" id="ptype" value="{$wrprofile}" />
	</body>
</html>

{literal}
	<script>
		document.getElementById("htmllink").innerHTML="";
		
		var name=document.getElementById("name").value;
		document.getElementById("wrname").innerHTML=name;

		var profiletype=document.getElementById("ptype").value;
		document.getElementById("wrprofile").src=profiletype;
	</script>
{/literal}