{if $smarty.get.profile eq 'invoice'}
<script type="text/javascript" src="/FO/script/contrib/profile-validate-invoice.js"></script>
{else}
<script type="text/javascript" src="/FO/script/contrib/profile-validate.js"></script>
{/if}	
{literal}
<style>
    #training_more_1 .popover-title, #job_more_1 .popover-title{ display: none; }
    .checkbox:hover{cursor: pointer;cursor: hand;}
</style>
<script type="text/javascript">
	$("#menu_profile").addClass("active");
/**profile pic uploading**/
$(function(){
		var btnUpload=$('.customfile');
		var status=$('#file_name');
		new AjaxUpload(btnUpload, {
			action: 'uploadprofilepic',
			name: 'uploadpic',
			onSubmit: function(file, ext){
				 if (! (ext && /^(jpg|jpeg|gif|png)$/.test(ext))){ 
                    // extension is not allowed 
					status.text("Please upload JPG,PNG and GIF files only.").css('color','#FF0000');
					return false;
					}

				 /*if (! (ext && /^(doc|docx|rtf)$/.test(ext))){ 
                    // extension is not allowed 
					status.html('Only doc,docx,rtf files are allowed').css('color','#FF0000');
					return false;
					}*/
				status.html('<img src="/FO/images/icon-image.gif" /> Uploading..');
			},
			onComplete: function(file, response){
				//On completion clear the status
				status.text('');
				$('#file_name').html('');
				
				//Add uploaded file to list
				var obj = $.parseJSON(response);
				var approot="/FO/";
				
				if(obj.status=="success"){
					$('#spec_file_name').val(file);
					
					$('#Cropimage').modal();
					var top=$(window).scrollTop();
					var box_top=$('#Cropimage').css('top', (parseInt(60) + ((top*2)/$(window).height())) + '%');
					//alert(approot+obj.path+obj.identifier+"_crop."+obj.ext+ '?' + (new Date()).getTime());
					$("#cropbox").attr('src','#');
					$(".jcrop-holder").remove();
					$("#cropbox").removeData('Jcrop');
					$("#cropbox").attr("src",approot+obj.path+obj.identifier+"_crop."+obj.ext+ '?' + (new Date()).getTime());
					$("#cropbox").show();
					$('#cropbox').Jcrop({
						aspectRatio: 1,
						addClass: 'jcrop-dark',
						setSelect: [ 60, 110, 150, 200 ],
						onSelect: updateCoords
					});
							
					if(file.length>25)
					$('#file_name').html(file.substr(0,25)+".. Uploaded").css('color','#006600');
					else
					$('#file_name').html(file+" Uploaded").css('color','#006600');
					
					//window.setTimeout('location.reload()', 10);
					
					
					
				}
				else if(obj.status=="smallfile"){
				
					$('#file_name').html("The image is too small, please upload another one").css('color','#FF0000');
				}
				else{
					$('#file_name').html('Error in upload').css('color','#FF0000');
				}
			}
		});
				
		jQuery('img').each(function(){
			jQuery(this).attr('src',jQuery(this).attr('src')+ '?' + (new Date()).getTime());
		});	
	
		//show update profile message
		var profile='{/literal}{$smarty.get.profile}{literal}';	
		if(profile=='invoice')
		{
			$("#profile-update").modal('show');	
			$("#profile-update").removeClass( "hide" ).addClass("in");
			//var scrollTop = $(window).scrollTop();
			//$("#profile-update").css("top",scrollTop);
			$("html, body").animate({ scrollTop: 0 }, "slow");
		}	
			
	});		
	
	/**toggle for payment infos**/	
	
	 $('input[type=radio]').live('click', function () {
		
		var payment_type = $("input:radio[name ='payment_type']:checked").val();		
		var payinfo=$('input:radio[name=payinfo]:checked').val();
		
		if (this.checked && $(this).val() == 'virement') 
		{	
			$("#c_out_uk").show();
			
		}
		else if (this.checked && $(this).val() == 'paypal') 
		{
			$("#c_out_uk").hide();			
		}
		
	});
	
	function switchzipcode(country)
	{
		if(country==156)
		{
			$("#ukzipcode").show();
			$("#otherzipcode").hide();
		}
		else
		{
			$("#ukzipcode").hide();
			$("#otherzipcode").show();
		}
	}
	
	
    /*added by naseer on 04-11-2015*/
    //this function will enable/disable respective inputs//
    function toggle_software_details(self_id){
        if($('#'+self_id).is(':checked'))
        {
            $('.'+self_id).prop("disabled",false);//enables textbox
        }
        else
        {
            $('.'+self_id).prop("disabled",true);//on unset checkbox disable textbox
        }
    }
    /*end of added by naseer */
</script>
{/literal}
<div class="container">
	 <!-- ajax use start -->
					<div id="Cropimage" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="cropimageLabel" aria-hidden="true">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3 id="cropimageLabel">Resize image</h3>
						</div>
						<div class="modal-body">
							{include file="Contrib/profile_image_crop.phtml"}
						</div>
					</div>
					<!-- ajax use end -->
    <div class="row-fluid">
		{if $actionmessages[0]}
			<div class="alert alert-success"><button data-dismiss="alert" class="close" type="button">&times;</button>
				<i class="icon-ok icon-white"></i> {$actionmessages[0]}.
			</div>  
		{/if}
		{if $selected_ao_count}
			<div class="span12" style="color:#F47D31;"><h2>Amend Profile: Complete your profile to access your selection</h2></div>
		{else}	
			<div class="span12"><h1>Amend profile
				<div class="pull-right">
					<a href="/contrib/private-profile" class="btn btn-small"><i class="icon-arrow-left"></i> Go back to my private profile</a>
					{if $cv_exists eq 'yes'}
						<a class="btn btn-small" href="/contrib/download-file?type=cv"><i class="icon-briefcase"></i> Mon CV</a>
					{/if}			
				</div>
				</h1>
			</div>
		{/if}	
	</div>
		
	<section id="skills-form">
		<form class="form-horizontal" method="POST" action="/contrib/save-profile/" id="contribProfile">
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My email address <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form">
								<label><input type="text" disabled placeholder="email" class="inline input-large" value="{$email}" name="email" id="email"></label>
								
							</div>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My password <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form">
								<label><input type="password" placeholder="password" class="inline input-large" value="{$password}" name="password" id="password"></label>
								
							</div>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Confirm password <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form">
								<label><input type="password" placeholder="password" class="inline input-large" value="{$password}" name="password2" id="password2"></label>
								
							</div>
						</div>
					</div>
				<!-- identity -->
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My ID <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form">
								<label>
								<select class="select-large" name="initial" id="initial">
									<option value="">I am</option>
									<option value="mr" {if $civ=='mr'} selected{/if}>Male</option>
									<option value="ms" {if $civ=='mrs' || $civ=='ms' } selected{/if}>Female</option>
								</select>
								</label>
								<label><input type="text" placeholder="My first name" class="inline input-large" value="{$fname}" name="first_name" id="first_name"></label>
								<label><input type="text" placeholder="My last name" class=" input-large" value="{$lname}" name="last_name" id="last_name"></label>
							</div>
						</div>
					</div>
					<!-- birthday -->

					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>My date of birth <span class="error">*</span></strong></label>
						<div class="controls span8">
							<div class="form-inline">
								<label>
									{html_select_date end_year="1910" start_year='+0' field_order="DMY" time=$dob class="input-small" field_separator="</label>&nbsp;<label>"}
								</label>	
							</div>
						</div>
					</div>
				<!--Picture --> 
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Profile photo</strong></label>
						<div class="controls span8 container-field">
							<div id="changePicture">
								<div class="span2">
									<div class="editor-container pull-left">
										<a href="/contrib/modify-profile" class="imgframe-large"><img id="profilepic" title="{$client_email}" src="{$profile_image}"></a>
									</div>
								</div>
								<div class="span9 offset1">
									<p>Update your photo :</p>
									<input type="file" class="span9" name="file" id="filePJ">
									<span id="file_name" class="help-block"></span>
									<span class="help-block">Image size: 90x90 </span>
								</div>
							</div>
						</div>  
					</div>
					
                    <!-- about me -->
                    <div class="control-group">
                    <label class="control-label span2 offset1" for=""><strong>Presentation text</strong></label>
                        <div class="controls span8" id="mytongue-mod">
                            <textarea class="span12" placeholder="100 characters minimum" name="self_details" id="self_details" >{$self_details}</textarea>
                        </div>
                    </div>
                    <!-- added by naseer on 26.11.2015-->
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Twitter ID <!--<span class="error">*</span>--></strong></label>
                        <div class="controls span8">
                            <div class="form">
                                <label><input type="text" placeholder="Twitter ID" class="inline input-large" value="{$twitter_id}" name="twitter_id" ></label>

                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Facebook ID <!--<span class="error">*</span>--></strong></label>
                        <div class="controls span8">
                            <div class="form">
                                <label><input type="text" placeholder="Facebook ID" class="inline input-large" value="{$facebook_id}" name="facebook_id" ></label>

                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Website/Blog <!--<span class="error">*</span>--></strong></label>
                        <div class="controls span8">
                            <div class="form">
                                <label><input type="text" placeholder="Website/Blog" class="inline input-large" value="{$website}" name="website"></label>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Bloc Statut</strong></label>
                        <div class="controls span8" id="mytongue-mod">
                            <label class="checkbox">
                                <input type="checkbox" {if $writer_preference == 'yes'}checked {/if} name="writer_preference">R&eacute;dacteur
                            </label>
                            <label class="checkbox">
                                <input type="checkbox" {if $translator == 'yes'}checked {/if} name="translator">Traducteur
                            </label>
                        </div>
                    </div>

<!--				</div>-->
<!--			</div>   -->


			<!-- Start, Languages module -->    
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Languages &amp; level <span class="error">*</span></strong></label>
						<div class="controls span8">    
							<select class="span5" name="language" id="language">
								<option value=''>Mother tongue</option>
								{html_options  options=$ep_language_list selected=$profile_mother_language}
							</select>
						</div>
						<div class="controls span8">
							{if $language_more|@count gt 0}
								{foreach from=$language_more key=lang item=percent name="moreLanguage}
									{assign var=lang_index value=$smarty.foreach.moreLanguage.index}
										<!-- Start, new language row -->
										<div class="addmore" id="language_more_{$lang_index}">  
											<button  class="close" type="button" id="language_close_{$lang_index}" {if $language_more|@count lt 2} style="display:none"{/if}>&times;</button>
												<div class="span5">
													<select class="span12 margintop" name="language_more[]">
														<option value="">Select a language</option>
														{html_options  options=$ep_language_list selected=$lang}
													</select>
												</div>
												<div class="skillstat span5 offset1">
													<div>
														<label for="slider-language_number_{$smarty.foreach.moreLanguage.index}" class="muted">Your level :</label>
														<input type="text" id="slider-language_number_{$smarty.foreach.moreLanguage.index}" value="{$percent}" name="lang_slider_more[]"/>
													</div>
													<div id="slider-language_{$smarty.foreach.moreLanguage.index}" class="lang_slider">{$percent}</div>
													<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Bilingual</span>
												</div>
										</div>
										<!-- end, new language row -->
								{/foreach}						
							
							{else}							
								<!-- Start, new language row --> 
								<div class="addmore" id="language_more_0">  
										<div class="span5">
											<select class="span12 margintop" name="language_more[]">
												<option value="">Select a language</option>
												{html_options  options=$ep_language_list}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-language_number_0" class="muted">Your level :</label>
												<input type="text" id="slider-language_number_0" name="lang_slider_more[]" value="50"/>
											</div>
											<div id="slider-language_0" class="lang_slider">50</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Bilingual</span>
										</div>
								</div>
								<!-- end, new language row -->
							{/if}

								<!-- start, add language row button -->
									<p class="addmore-button" id="addmore_lang_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add a language</a></p>
								<!-- end, add language row button -->
							<!-- end, add language row -->
						</div>           
					</div> 
				</div>
			</div>

			<!-- End, Languages module --> 


			<!-- Start, Skills module -->    
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Skills &amp; level <span class="error">*</span></strong></label>

						<div class="controls span8" >
							{if $category_more|@count gt 0}
								{foreach from=$category_more key=kcategory item=percent name="moreSkills}
								{assign var=skill_index value=$smarty.foreach.moreSkills.index}
									<!-- Start, new skill row -->     
									<div class="addmore" id="skill_more_{$skill_index}">  
										<button  class="close" type="button" id="skill_close_{$skill_index}" {if $category_more|@count lt 2} style="display:none"{/if}>&times;</button>
										<div class="span5">
											<select class="required span12 margintop" name="ep_category[]" id="ep_category_{$smarty.foreach.moreSkills.index}">
												<option value="">Select a skill</option>
												{html_options  options=$ep_categories_list selected=$kcategory}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-skill_number_{$smarty.foreach.moreSkills.index}" class="muted">Your level</label>
												<input type="text" id="slider-skill_number_{$smarty.foreach.moreSkills.index}" value="{$percent}" name="category_slider_more[]"/>
											</div>
											<div id="slider-skill_{$smarty.foreach.moreSkills.index}" class="skill_slider">{$percent}</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Expert</span>
										</div>
									</div>
									<!-- end, new skill row -->
								{/foreach}
							{else}
									<!-- Start, new skill row -->     
									<div class="addmore" id="skill_more_0">  
										<div class="span5">
											<select class="span12 margintop" name="ep_category[]" id="ep_category_0">
												<option value="">Select a skill</option>
												{html_options  options=$ep_categories_list selected=$category}
											</select>
										</div>
										<div class="skillstat span5 offset1">
											<div>
												<label for="slider-skill_number_0" class="muted">Your level :</label>
												<input type="text" id="slider-skill_number_0" name="category_slider_more[]" value="50"/>
											</div>
											<div id="slider-skill_0" class="skill_slider">50</div>
											<span class="pull-left legend muted">Beginner</span> <span class="pull-right legend muted">Expert</span>
										</div>
									</div>
									<!-- end, new skill row -->	
							{/if}		
								<!-- start, add language row button -->
									<p class="addmore-button" id="addmore_skill_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add a skill</a></p>
								<!-- end, add language row button -->
							<!-- end, new skill row -->
						</div>           
					</div> 
				</div>
				<!-- End, Skills module -->   
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Software Ownership and Experience Level</strong></label>
                        <div class="controls span8">
                            <table class="table table-bordered">
                                <tr>
                                    <td></td>
                                    <td>Beginner</td>
                                    <td>Intermediate</td>
                                    <td>Advanced</td>
                                    <td>I own it</td>
                                </tr>
                                {assign var="previous_software" val=""}
                                {foreach from=$ep_software_array key=softwarekey item=software name="SoftwareList"}
                                {assign var=s_index value=$smarty.foreach.SoftwareList.index+1}
                                    {if $previous_software neq $software[0]}
                                        <tr style="background-color: #DDDDDD;">
                                            <td><b>{$software[0]}</b></td>
                                            <td colspan="4"></td>
                                        </tr>
                                    {/if}
                                    <!--code to check if the value is saved in DB-->
                                    {assign var=check value=0}
                                    {assign var=condition value="false"}
                                    {assign var=level value="false"}
                                    {assign var=own value="false"}
                                    {while $check < $software_list_count}
                                        {if $software_list[$check][0] eq $softwarekey}
                                            {assign var=condition value="true"}
                                            {assign var=level value=$software_list[$check][1]}
                                            {assign var=own value=$software_list[$check][2]}
                                        {/if}
                                        {assign var=check value=$check+1}
                                    {/while}
                                    <!-- end of code to check if the value is saved in DB -->
                                    {if $condition eq "true"}
                                        <tr>
                                            <td>
                                                <label class="checkbox">
                                                    <input type="checkbox" name="software_name[{$s_index}]" id="software_{$s_index}" value="{$softwarekey}" checked onclick="toggle_software_details(this.id);" />{$software[1]}
                                                </label>
                                            </td>
                                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="beginner" {if $level eq 'beginner'}checked{/if}/></label></td>
                                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="intermediate" {if $level eq 'intermediate'}checked{/if}/></label></td>
                                            <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="advanced" {if $level eq 'advanced'}checked{/if}/></label></td>
                                            <td><label class="checkbox"><input type="checkbox" name="software_own[{$s_index}]" class="software_{$s_index}" {if $own eq "on"}checked{/if}/></label></td>
                                        </tr>
                                    {else}
                                            <tr>

                                                <td>
                                                    <label class="checkbox">
                                                        <input type="checkbox" name="software_name[{$s_index}]" id="software_{$s_index}" value="{$softwarekey}" onclick="toggle_software_details(this.id);"  />{$software[1]}
                                                    </label>
                                                </td>

                                                <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="beginner" disabled/></label></td>
                                                <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="intermediate" disabled/></label></td>
                                                <td><label class="radio "><input type="radio" name="software_level[{$s_index}]" class="software_{$s_index}" value="advanced" disabled/></label></td>
                                                <td><label class="checkbox"><input type="checkbox" name="software_own[{$s_index}]" class="software_{$s_index}" disabled/></label></td>
                                            </tr>
                                    {/if}
                                    {*{/for}*}
                                    {assign var="previous_software" value=$software[0]}
                                {/foreach}

                            </table>

                        </div>
                    </div>
                </div>
            </div>

			<!-- Start, Job module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Work Experience <span class="error">*</span></strong>
							<br><span id="job_error"></span>
						</label>

						<div class="controls span8">
							{if $jobDetails|@count gt 0}
								{foreach from=$jobDetails item=job name="job_details"}
									{assign var=job_index value=$smarty.foreach.job_details.index+1}
									
									<!-- Start, job row -->
									<div class="addmore" id="job_more_{$job_index}">
										
										<button  class="close" type="button" id="job_close_{$job_index}" rel="{$job.identifier}"  {if $jobDetails|@count lt 2} style="display:none"{/if}>&times;</button>
										
										<label><input class="span5" id="JobName_{$job_index}" value="{$job.title}" name="job_title[]" placeholder="Job title"></label>
										<label><input class="span5" id="CompanyName_{$job_index}" value="{$job.institute}" name="job_institute[]" placeholder="Company name"></label>
										<select class="span5" name="ep_job[]" id="ep_job_{$job_index}">
											<option value="">Select contract type</option>
											<option value="cdi" {if $job.contract=='cdi'}selected{/if}>Full-time</option>
											<option value="cdd" {if $job.contract=='cdd'}selected{/if}>Part-time</option>
											<option value="freelance" {if $job.contract=='freelance'}selected{/if}>Freelance</option>
											<option value="intern" {if $job.contract=='intern'}selected{/if}>Temporary</option>
											<option value="stage" {if $job.contract=='stage'}selected{/if}>Placement/Training</option>
										</select>
										<div class="clearfix">
											<div class="container-field span5">
												<label>
													<span class="span3">Start date</span>
												</label>												
													<select class="input-small inline" name="start_month[]">
														<option value="1" {if $job.from_month=='1'}selected{/if}>January</option>
														<option value="2" {if $job.from_month=='2'}selected{/if}>February</option>
														<option value="3" {if $job.from_month=='3'}selected{/if}>March</option>
														<option value="4" {if $job.from_month=='4'}selected{/if}>April</option>
														<option value="5" {if $job.from_month=='5'}selected{/if}>May</option>
														<option value="6" {if $job.from_month=='6'}selected{/if}>June</option>
														<option value="7" {if $job.from_month=='7'}selected{/if}>July</option>
														<option value="8" {if $job.from_month=='8'}selected{/if}>August</option>
														<option value="9" {if $job.from_month=='9'}selected{/if}>September</option>
														<option value="10" {if $job.from_month=='10'}selected{/if}>October</option>
														<option value="11" {if $job.from_month=='11'}selected{/if}>November</option>
														<option value="12" {if $job.from_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="start_year_{$job_index}" placeholder="Year" value="{$job.from_year}" name="start_year[]" maxlength="4">
												
												<div class="collapse {if $job.still_working !='yes'} in {/if}" id="stillWorkingThere_{$job_index}">
													<label> 
														<span class="span3">End date</span>
													</label>
														<select class="input-small inline" name="end_month[]">
															<option value="1" {if $job.to_month=='1'}selected{/if}>January</option>
															<option value="2" {if $job.to_month=='2'}selected{/if}>February</option>
															<option value="3" {if $job.to_month=='3'}selected{/if}>March</option>
															<option value="4" {if $job.to_month=='4'}selected{/if}>April</option>
															<option value="5" {if $job.to_month=='5'}selected{/if}>May</option>
															<option value="6" {if $job.to_month=='6'}selected{/if}>June</option>
															<option value="7" {if $job.to_month=='7'}selected{/if}>July</option>
															<option value="8" {if $job.to_month=='8'}selected{/if}>August</option>
															<option value="9" {if $job.to_month=='9'}selected{/if}>September</option>
															<option value="10" {if $job.to_month=='10'}selected{/if}>October</option>
															<option value="11" {if $job.to_month=='11'}selected{/if}>November</option>
															<option value="12" {if $job.to_month=='12'}selected{/if}>December</option>
														</select>
														&nbsp;&nbsp;<input class="input-small inline" id="end_year_{$job_index}" placeholder="Year" value="{$job.to_year}" maxlength="4" name="end_year[]">
																										
												</div>
												<label class="checkbox">
													<input type="checkbox" id="still_working_{$job_index}" data-target="#stillWorkingThere_1" data-toggle="collapse" {if $job.still_working =='yes'} checked {/if}  name="still_working[]">I still work here
												</label>
												<input type="hidden" name="job_identifier[]" value="{$job.identifier}">
											</div>
										</div> 
									</div>
									<!-- end, job row -->
								{/foreach}
							{else}		
								<!-- Start, job row -->
								<div class="addmore" id="job_more_1">
									<label><input class="span5" id="JobName_1" name="job_title[]" placeholder="Job title"></label>
									<label><input class="span5" id="CompanyName_1" name="job_institute[]" placeholder="Company name"></label>
									<select class="span5" name="ep_job[]" id="ep_job_1">
										<option value="">Select contract type</option>
										<option value="cdi">Full-time</option>
										<option value="cdd">Part-time</option>
										<option value="freelance">Freelance</option>
										<option value="intern">Temporary</option>
										<option value="stage">Placement/Training</option>
									</select>
									<div class="clearfix">
										<div class="container-field span5">
											<label>
												<span class="span3">Start date</span> 
											</label>	
												<select class="input-small inline" name="start_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="start_year_1" placeholder="Year" name="start_year[]" maxlength="4">
											
											<div class="collapse in" id="stillWorkingThere_1">
												<label> 
													<span class="span3">End date</span> 
												</label>	
													<select class="input-small inline" name="end_month[]">
														<option value="1" selected>January</option>
														<option value="2">February</option>
														<option value="3">March</option>
														<option value="4">April</option>
														<option value="5">May</option>
														<option value="6">June</option>
														<option value="7">July</option>
														<option value="8">August</option>
														<option value="9">September</option>
														<option value="10">October</option>
														<option value="11">November</option>
														<option value="12">December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="end_year_1" placeholder="Year" maxlength="4" name="end_year[]">
												
											</div>
											<label class="checkbox">
												<input type="checkbox" id="still_working_1" data-target="#stillWorkingThere_1" data-toggle="collapse" name="still_working[]">I still work here
											</label>
										</div>
									</div> 
								</div>
								<!-- end, job row -->
							{/if}	
							<p class="addmore-button" id="addmore_job_link"><a class="btn btn-link btn-small"><i class="icon-plus"></i> Add an experience</a></p>  
						</div>
					</div>
				</div>
			</div>  
			<!-- End, Job -->
			<!-- Start, Training module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Training/Education <span class="error">*</span></strong>
							<br><span id="edu_error"></span>
						</label>
						<div class="controls span8">
							{if $educationDetails|@count gt 0}
								{foreach from=$educationDetails item=education name="edu_details"}
									{assign var=edu_index value=$smarty.foreach.edu_details.index+1}
									<!-- Start, School row -->
									<div class="addmore" id="training_more_{$edu_index}">
										 	
											<button  class="close" type="button" id="training_close_{$edu_index}" rel="{$education.identifier}" {if  $educationDetails|@count lt 2} style="display:none"{/if}>&times;</button>
											
										<label><input class="span5" id="trainingName_{$edu_index}" value="{$education.title}" name="training_title[]" placeholder="Title of training/education"></label>
										<label><input class="span5" id="trainingSchoolName_{$edu_index}" value="{$education.institute}" name="training_institute[]" placeholder="School, University, etc..."></label>
										<div class="clearfix">  
											<div class="container-field span5">
												<label>
													<span class="span3">Start date</span> 
												</label>	
													<select class="input-small inline" name="start_train_month[]">
														<option value="1" {if $education.from_month=='1'}selected{/if}>January</option>
														<option value="2" {if $education.from_month=='2'}selected{/if}>February</option>
														<option value="3" {if $education.from_month=='3'}selected{/if}>March</option>
														<option value="4" {if $education.from_month=='4'}selected{/if}>April</option>
														<option value="5" {if $education.from_month=='5'}selected{/if}>May</option>
														<option value="6" {if $education.from_month=='6'}selected{/if}>June</option>
														<option value="7" {if $education.from_month=='7'}selected{/if}>July</option>
														<option value="8" {if $education.from_month=='8'}selected{/if}>August</option>
														<option value="9" {if $education.from_month=='9'}selected{/if}>September</option>
														<option value="10" {if $education.from_month=='10'}selected{/if}>October</option>
														<option value="11" {if $education.from_month=='11'}selected{/if}>November</option>
														<option value="12" {if $education.from_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" placeholder="Year" id="start_train_year_{$edu_index}" value="{$education.from_year}" name="start_train_year[]">
												
												<div class="collapse  {if $education.still_working !='yes'} in {/if}" id="stillTrainingThere_{$edu_index}">
													<label>
														<span class="span3">End date</span> 
													</label>	
														<select class="input-small inline" name="end_train_month[]">
														<option value="1" {if $education.to_month=='1'}selected{/if}>January</option>
														<option value="2" {if $education.to_month=='2'}selected{/if}>February</option>
														<option value="3" {if $education.to_month=='3'}selected{/if}>March</option>
														<option value="4" {if $education.to_month=='4'}selected{/if}>April</option>
														<option value="5" {if $education.to_month=='5'}selected{/if}>May</option>
														<option value="6" {if $education.to_month=='6'}selected{/if}>June</option>
														<option value="7" {if $education.to_month=='7'}selected{/if}>July</option>
														<option value="8" {if $education.to_month=='8'}selected{/if}>August</option>
														<option value="9" {if $education.to_month=='9'}selected{/if}>September</option>
														<option value="10" {if $education.to_month=='10'}selected{/if}>October</option>
														<option value="11" {if $education.to_month=='11'}selected{/if}>November</option>
														<option value="12" {if $education.to_month=='12'}selected{/if}>December</option>
													</select>
													&nbsp;&nbsp;<input class="input-small inline" id="end_train_year_{$edu_index}" placeholder="Year" value="{$education.to_year}" name="end_train_year[]" >
													
												</div>
												<label class="checkbox">
													<input type="checkbox" id="still_training_{$edu_index}" data-target="#stillTrainingThere_{$edu_index}" name="still_training[]" data-toggle="collapse" {if $education.still_working =='yes'} checked {/if}>I am still in training/education
												</label>
												<input type="hidden" name="training_identifier[]" value="{$education.identifier}">
											</div>
										</div> 
									</div>
									<!-- end, school row -->	
									
								{/foreach}
							{else}	
								<!-- Start, School row -->
								<div class="addmore" id="training_more_1">
									<label><input class="span5" id="trainingName_1" name="training_title[]" placeholder="Title of training/education"></label>
									<label><input class="span5" id="trainingSchoolName_1" name="training_institute[]" placeholder="School, University, etc..."></label>
									<div class="clearfix">  
										<div class="container-field span5">
											<label>
												<span class="span3">Start date</span> 
											</label>	
												<select class="input-small inline" name="start_train_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="start_train_year_1" placeholder="Year" name="start_train_year[]">
											
											<div class="collapse in" id="stillTrainingThere_1">
												<label>
													<span class="span3">End date</span> 
												</label>	
													<select class="input-small inline" name="end_train_month[]">
													<option value="1" selected>January</option>
													<option value="2">February</option>
													<option value="3">March</option>
													<option value="4">April</option>
													<option value="5">May</option>
													<option value="6">June</option>
													<option value="7">July</option>
													<option value="8">August</option>
													<option value="9">September</option>
													<option value="10">October</option>
													<option value="11">November</option>
													<option value="12">December</option>
												</select>
												&nbsp;&nbsp;<input class="input-small inline" id="end_train_year_1" placeholder="Year" name="end_train_year[]">
												</label>
											</div>
											<label class="checkbox">
												<input type="checkbox" id="still_training_1" data-target="#stillTrainingThere_1" name="still_training[]" data-toggle="collapse">I am still in training/education
											</label>
										</div>
									</div> 
								</div>
								<!-- end, school row -->
							{/if}	
							<p class="addmore-button" id="addmore_training_link"><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Add training/education</a></p>  
						</div>
					</div>
				</div>
			</div>  
			<!-- End, Training module -->
			<!-- Start, personal info module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Personal information <span class="error">*</span></strong></label>    
						<div class="controls span8">
							<label>
								<select class="span5" name="nationality" id="nationality">
									<option value="">Nationality</option>
									{html_options  options=$ep_nationality_list selected=$nationality}									
								</select>
							</label>
							<label><input class="span5" id="address" name="address" placeholder="Address" value="{$address}"></label>
							<label><input class="span5" id="phone_number" name="phone_number" placeholder="Phone" value="{$phonenumber}"></label>
							<label><input class="span5" id="city" name="city" placeholder="City" value="{$city}"></label>
							<div id="ukzipcode" {if $country!=156}style="display:none"{/if}>
								<label>
									<input class="span2" id="zipcode1" name="zipcode1" placeholder="Postcode" value="{$zipcode1}" maxlength="4"/>
									<input class="span2" id="zipcode2" name="zipcode2" placeholder="Postcode" value="{$zipcode2}" maxlength="3"/>
									<label for="zipcode1" generated="true" class="error"></label>
									<label for="zipcode2" generated="true" class="error"></label>
								</label>
							</div>
							<div id="otherzipcode" {if $country==156}style="display:none"{/if}>
								<label>
								<input class="span5" id="zipcode" name="zipcode" placeholder="Postcode" value="{$zipcode}" />
								</label>
							</div>
							<label>
								<select class="span5" name="country" id="country" Onchange="switchzipcode(this.value)">
									<option value="">Country</option>
									{html_options  options=$ep_pays_list selected=$country}
								</select>
							</label>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, personal info module -->

			<!-- Start, billing info module -->
			<div class="mod" id="pay_info_type">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Subject to VAT (business - entrepreneur)<span class="error">*</span></strong></label>    
						<div class="controls span8">
							<label class="radio">
								<input type="radio" name="entreprise" value="yes" {if $entreprise=='yes'} checked {/if}>Yes
							</label>
							<label class="radio">
								<input type="radio" name="entreprise" value="no" {if $entreprise=='no'} checked {/if}>No
							</label>
							
							<br>
							<span id="payinfo_error"></span>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, billing info module -->
			<!-- Start, payment info module -->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Preferred payment method {if $smarty.get.profile eq 'invoice'}<span class="error">*</span>{/if} </strong></label>    
						<div class="controls span8">
							<label class="radio">
								<input type="radio" type="radio" value="paypal" {if $payment_type == 'paypal'}checked class="collapsed"{/if} name="payment_type" data-target="#paypalemail" data-toggle="collapse">Paypal
							</label>
							<!-- if Payapl is true, display the input "paypal email" -->
							<div id="paypalemail" {if $payment_type=='paypal'} class="collapse in out" {else} class="collapse out" {/if} >
								<i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="paypal email" name="paypal_id" id="paypal_id" value="{$paypal_id}">
							</div>
							{*<label class="radio" id="cheque_radio" {if $pay_info_type=='out_uk' || $country!=156} style="display:none" {/if}>
								<input type="radio" value="cheque" {if $payment_type == 'cheque'}checked{/if} name="payment_type">Cheque
							</label>*}
							<label class="radio">
								<input type="radio" value="virement" {if $payment_type == 'virement'}checked{/if} name="payment_type">Bank transfer
							</label>
							<!-- if virement is true, display the input "paypal email" -->
							<div id="virementId" {if $payment_type=='virement'} class="collapse in out" {else} class="collapse in" {/if} >		
								<div id="c_out_uk" {if $payment_type=='virement' }style="display:block"{else}style="display:none"{/if}>
									<i class="icon-arrow-right"></i>
									<input type="text" value="{$rib_id_6}" class="span3" placeholder="BIC" name="rib_id_6" id="rib_id_6"/>
									<input type="text" value="{$rib_id_7}" class="span3" placeholder="IBAN" name="rib_id_7" id="rib_id_7"/>
									<input type="text" value="{$bank_account_name}" class="span4" placeholder="Account name" name="bank_account_name" id="bank_account_name"/>
								</div>
							</div>
							<br>
							<span id="payment_error"></span>
						</div>
					</div> 
				</div>
			</div>

			<!-- End, payment info module -->
			<!-- News letter/Auto email subscribe-->
			<div class="mod">
				<div class="row-fluid">
					<div class="control-group">
						<label class="control-label span2 offset1" for=""><strong>Subscriptions</strong></label>    
						<div class="controls span8">
							<label class="checkbox">
								<input type="checkbox" {if $subscribe == 'yes'}checked {/if} name="subscribe">Newsletter
							</label>
							<label class="checkbox">
								<input type="checkbox" {if $alert_subscribe == 'yes'}checked {/if} name="alert_subscribe">Alerts by email
							</label>
						</div>
					</div>
				</div>
			</div>	
			<!--End  News letter/Auto email subscribe-->
			

			<div class="mod">
				<div class="pull-right">
					<button class="btn inline" id="cancel">Cancel</button> 
					<button class="btn btn-primary inline"><i class="icon-refresh icon-white"></i> Save</button>
				</div>
			</div>
		</form>
	</section>
</div>


<!-- ajax use start -->
<div id="profile-update" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Amend profile</h3>
	</div>
	<div class="modal-body">
		<p>Our invoicing system has changed ! </p>
		<p>Please update your profile and state your preferred payment method, and with VAT or not.</p>
		<p>Best,</p>
		<p>Edit-place Team</p>
	</div>
</div>
<!-- ajax use end -->
