<!--$finished to display finshed Ao style
$upcmoing to check upcoming ao block styles--> 
{literal}
<script type="text/javascript">
	var cur_date={/literal}{$smarty.now}{literal};
	var js_date=(new Date().getTime())/ 1000;
	var diff_date=Math.floor(js_date-cur_date);
// tooltip activation
    $("[rel=tooltip]").tooltip();
	$("[rel=popover]").popover();	
	startTimer('time1','text1'); //timer ids starting with
	startTimer('time2','text2');//timer ids starting with
</script>
{/literal}
{if $articleDetails | @count gt 0}
	{foreach from=$articleDetails item=article name=details}
		<section id="a_o">
			{if $mission_type eq 'premium'}
				<div class="mp">
					{if $article.missiontest eq 'yes'}
						<span class="label label-test-mission" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right"><i class="icon-star icon-white"></i>  Staffing</span>
					{else}
						<span class="label label-premium" data-original-title="Mission guaranteed by Edit-place" rel="tooltip" data-placement="right">Premium Mission</span>
					{/if}
			{elseif $mission_type eq 'nopremium'}	
				<div class="dl">
					{if $article.missiontest eq 'yes'}
						<span class="label label-test-mission" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right"><i class="icon-star icon-white"></i>  Staffing</span>
					{else}
						<span class="label label-quote" data-original-title="You will work directly with the client" rel="tooltip" data-placement="right">Freedom Mission</span>
					{/if}
			{/if}	
			{if $article.view_to eq 'sc'}
				<span data-original-title="Senior level" data-content="I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Senior</span>
			{elseif $article.view_to eq 'jc'}
				<span data-original-title="Available to Junior" data-content="At least 1 article accepted on Edit-place" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Junior</span>
			{elseif $article.view_to eq 'jc0'}
				<span data-original-title="Available to Beginner" data-content="No articles accepted on Edit-place yet" rel="popover" data-trigger="hover" data-placement="right" class="label label-level"><i class="icon-bookmark"></i>Beginner</span>	
			{/if}			
			{if $article.link_quiz eq 'yes' && $article.quiz}
				<span class="label label-inverse" data-original-title="Participation soumis &agrave; un Quizz" rel="tooltip" data-placement="right">Quizz</span>
			{/if}
				<h2>{$article.title} {$article.picon}</h2>				

				<div class="summary clearfix">
					<ul class="unstyled">
						<li><strong>Call to writers</strong> <span class="bullet">&#9679;</span></li>
						<li> Language : <img class="flag flag-{$article.language}" src="/FO/images/shim.gif" data-placement="left" rel="tooltip" data-original-title="{$article.language_name}"> <span class="bullet">&#9679;</span></li>
						<li>Category : {$article.category} <span class="bullet">&#9679;</span></li>
						<li>Nb. Of words : {$article.num_min} - {$article.num_max} / article<span class="bullet">&#9679;</span></li>
						<li><a href="#comment" class="scroll" id="comment_count_1"><i class="icon-comment"></i> {$commentCount}</a></li>
						{if $article.spec_exists eq 'yes'}
							<li class="pull-right"><a href="/contrib/download-file?type=clientbrief&article_id={$article.articleid}" class="btn btn-small btn-success"><i class="icon-white icon-circle-arrow-down"></i> Download the client brief</a></li>
						{/if}	
					</ul>
				</div>

				<div class="a_o-details">
					<!-- start, colonne generale -->
					<div class="row-fluid">
						<div class="span7">
							<!-- start, colonne stat -->
							<div class="row-fluid stat-block">
								<div class="span4 section">Time remaining
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
										
									{elseif $finished  eq 'yes'}
										Termin&eacute;
									{else}	
										<span id="time1_{$article.articleid}_{$article.timestamp}">
											<span id="text1_{$article.articleid}_{$article.timestamp}">{$article.timestamp}</span>
										</span>
									{/if}	
								</p>
								</div>
								<div class="span4 section">Production time
								<p>
									{if $upcoming eq 'yes'}
										&#9679;&#9679;&#9679;
									{else}
										{$article.article_submit_time_text}
									{/if}	
								</p>
								</div>
								<div class="span4 section">Client<p><img src="{$article.client_pic}"  class="logo"/></p></div>
							</div>
							<div class="row-fluid note">
								<div class="span12">
									{if $mission_type eq 'premium'}
										<p><i class="icon-info-sign icon-white"></i> This mission is guaranteed by Edit-place. If you are selected, you are guaranteed to write immediately</p>
									{elseif $mission_type eq 'nopremium'}																			
										<p><i class="icon-info-sign icon-white"></i> <strong>Try your luck! Please note that this may be a simple information-gathering exercise or a full writing mission.</p>
									{/if}		
								</div>
							</div>
							<!-- end, colonne stat -->
						</div>
						<div class="span5">
							<table class="table table-hover">
							{if $upcoming eq 'yes'}
								{if $mission_type eq 'premium' OR ($article.AOtype eq 'private' && $article.price_max)}
									<tr><td class="title">Price Range</td><td class="countdown"><em>{$article.price_min|zero_cut:2} - {$article.price_max|zero_cut:2} 
									{if $article.currency eq 'euro'	}
										&euro;
									{else}
										&pound;
									{/if}
									</em></td></tr>
								{/if}
								<tr><td class="title">Open offer</td><td class="countdown">{$article.publishtime_format}</td></tr>
								<tr>
									<td colspan="2" class="cta" >
										<span id="alert_{$article.deliveryid}">											
											{if $article.alert_subscribe eq 'no'}
												<button class="btn" onclick="subscribeAOAlert('{$article.deliveryid}','yes','article');"><i class="icon-bell"></i> Receive an alert</button>
											{elseif $article.alert_subscribe eq 'yes'}
												<a class="btn btn-small btn-primary" onclick="subscribeAOAlert('{$article.deliveryid}','no','article');"><i class="icon-remove icon-white"></i> Alert set</a>
											{/if}
										</span>
										
									</td>
								</tr>
							{else}
								<tr><td class="title">Contributors {$article.picon}</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="Contributor information" data-placement="left" data-html="true" {if $article.participants_pic} data-content="{$article.participants_pic}" data-trigger="hover"{/if}>{$article.participants}</a></em></td></tr>							
								
								{if $mission_type eq 'premium' OR ($article.AOtype eq 'private' && $article.price_max)}
									<tr><td class="title">Price Range</td><td class="countdown">{if $article.pricedisplay=="yes"}<em>{$article.price_min|zero_cut:2} - {$article.price_max|zero_cut:2} 
									{if $article.currency eq 'euro'	}
										&euro;
									{else}
										&pound;
									{/if}
									</em>{else}/{/if}</td></tr>
								{/if}
								{if $article.pricedisplay=="yes"}
								<tr><td class="title">Last rate offered</td><td class="countdown"><em><a href="#" rel="popover" data-original-title="All offered rates" data-placement="left" data-html="true" {if $article.participants_price} data-content="{$article.participants_price}" data-trigger="hover"{/if}>
								{if $article.latestPrice} 
									{$article.latestPrice} 
									{if $article.currency eq 'euro'	}
										&euro;
									{else}
										&pound;
									{/if}
								{else}
									NA
								{/if}	
								</a></em></td></tr>	
								{/if}	
								{if $finished  eq 'yes'}
									<tr class="warning">
										<td colspan="2" class="cta"><strong><i class="icon-warning-sign"></i> Participation deadline expired</strong></td>
									</tr>
								{elseif $no_permission eq 'yes'}
									<tr class="warning">
											<td colspan="2" class="cta"><strong><i class="icon-warning-sign"></i> Sorry! The offer is reserved exclusively to 
											{if $article.view_to eq 'sc'}
												<span class="label label-level"><i class="icon-bookmark"></i>Senior</span>
											{elseif $article.view_to eq 'jc'}
												<span class="label label-level"><i class="icon-bookmark"></i>Junior</span>
											{elseif $article.view_to eq 'jc0'}
												<span class="label label-level"><i class="icon-bookmark"></i>Beginner</span>												
											{elseif $article.view_to eq 'sc,jc' OR $article.view_to eq 'jc,sc' }
												<span class="label label-level"><i class="icon-bookmark"></i>Senior</span><span class="label label-level"><i class="icon-bookmark"></i>Junior</span>
											{/if}
											</strong></td>
									</tr>
								{elseif !$request_from}
									<tr><td colspan="2" class="cta" id="tender_select_{$article.articleid}">
									
									{if $article.display eq 'no' || $disabled eq 'yes'}
										<button class="btn btn-large btn-primary disabled">Post added</button>	
									{elseif $article.attended eq 'YES'}								
										<button  onClick="fnCartModifiers('remove','{$article.articleid}','','{$article.deliveryid}');" class="btn btn-large btn-danger">Post added</button>
									{elseif $article.attended eq 'NO'}
										<button  onClick="fnCartModifiers('add','{$article.articleid}','','{$article.deliveryid}');" class="btn btn-large btn-primary">Add to my selection</button>
									{/if}	
									</td></tr>
								{/if}	
							{/if}	
							</table>
						</div>
					</div>
					<!-- end, colonne generale -->
				</div>
				{if $no_permission eq 'yes'}
					{include file="Contrib/mission-badStatus.phtml"}
				{/if}
				{if !$finished && !$no_permission}
					{include file="Contrib/article-comments.phtml"}
				{/if}	
			</div>
		</section>
		<a href="#brand" class="pull-right btn btn-small disabled anchor-top scroll"><i class="icon-arrow-up"></i></a>
		<div id = "confirmDiv"></div>
		{include file="Contrib/popup_confirm_selection.phtml"}
		
		<!--Quiz Confirmation modal-->
		<div id="gotoQuizz" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="myModalLabel">Pre-selection quiz</h3>
			</div>
			<div class="modal-body">
				<p> To add this offer to your selection, you must complete a quiz on the related theme.</p>
				<p><i class="icon-time"></i>  You will have <strong>{$article.quiz_duration} minutes</strong> to answer the questions. Ready ?</p> 
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
				<a class="btn btn-primary" data-target="#playQuizz-ajax" data-toggle="modal" role="button" href="/quiz/participate-quiz?article_id={$article.articleid}&quiz_identifier={$article.quiz}" id="btnPlayQuizz">Start the quiz</a>
				
			</div>
		</div>
		
	{/foreach}
{else}
<section>
	<div class="row-fluid">
		<div class="pull-center span10 offset1">
			<p class="text-error lead">You cannot take part in this mission.</p>
		</div>
	</div>
</section>
{/if}
{literal}
<script>
 	$(".scroll").click(function(event){		
		event.preventDefault();
		$('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
	});
	$('#btnPlayQuizz').click(function () {
		
		/* $('#playQuizz-ajax').modal(
		{
				remote: 'quizz.html'
		}
    	);	
		$('#playQuizz-ajax').modal('show'); */
		$('#gotoQuizz').modal('hide');
		$('#viewOffer-ajax').modal('hide');
		
		
		});	
</script>	
{/literal}