 <section id="help" name="help">
    <div class="container">
		<div class="row-fluid">
			<div class="mod">
				<h3>How does it work ?</h3>
				<ul class="nav nav-pills" id="helpTab">
					<li class="active"><a href="#type"><span class="licon licon-file"></span>Type of offers</a></li>
					<li><a href="#participant"><span class="licon licon-participant"></span>Contributors</a></li>
					<li><a href="#timing"><span class="licon licon-timing"></span>Time remaining</a></li>
					<li><a href="#pricing"><span class="licon licon-pricing"></span>Price range</a></li>
					<li><a href="#validation"><span class="licon licon-selection"></span>Approval of article and invoicing</a></li>
				</ul>
				 <hr>
				<div class="tab-content">
					<div class="tab-pane active" id="type">
						<h4><span class="label label-premium"><i class="icon-ok icon-white"> </i></span> Premium mission</h4>
						<p>Premium missions are exclusively <strong>managed by Edit-place</strong>. </p>
						<p>If you are selected for a premium mission, <strong>you are guaranteed to work</strong> on the relevant article and to be paid if your content follows the editorial guidelines/brief and desired tone/style.</p>
						<p>You can distinguish them thanks to the key on the left under available offers on Edit-place. If you take part in an offer you must wait for the confirmation email, stating you can start writing. If your profile does not fit or another writer has already been selected for the offer, you will also receive an email to inform you accordingly.</p>
						<hr>
						<h4><span class="label label-quote"><i class="icon-ok icon-white"> </i></span> Freedom mission</h4>
						<p>Freedom missions are <strong>exclusively managed by the client</strong> using the Edit-place platform. These clients publish their quote request for free. So in the first instance, it can be a simple information gathering exercise, or a full request resulting in a writing offer and recruitment of writers.</p>
						<p>You work directly with the client and not with Edit-place, therefore you should direct all your questions and issues to the client. Edit-place will however act as a mediator between you and the client in the event of disputes/issues.</p>
						<p>You can contact the client by email through your messages section in your Edit-place account. If you are selected, the client will have access to the email address and phone number published on your profile.</p>
						<p>  You can distinguish Freedom missions from Premium missions thanks to the key on the left under available offers on Edit-place. If you are selected by the client to write an article, you will receive a confirmation email and can start writing.</p>
						<hr>
							<h4><span class="label label-quote-premium"><i class="icon-ok icon-white"> </i></span> Premium Quote</h4>
						<p>As this is only a quote request, the contribution limit does not apply to premium quotes. If the quote becomes a Premium mission, the best quotes will be given an exclusive deadline to take part in the Premium mission and to offer a rate again.</p>
						
					</div>
					<div class="tab-pane" id="participant">
						<div class="row-fluid">
							<div class="span6">
						<h4><span class="label label-premium"><i class="icon-ok icon-white"> </i></span> Premium Mission</h4>
						<p>Depending on your experience with the platform, you can take part in less or more missions. Therefore you should choose them carefully. The number of contributions at any one time is set at 3 by default. You will receive an email, should this limit change.<br>As premium missions automatically end up in writing jobs, contributors will be selected within the 2 hours following the quote request deadline. If you are not selected, the mission is removed from your number of contributions. If you are selected, the mission is only removed from your number of contributions once the article sent has been approved by Edit-place.</p>
						<hr>
						<h4><span class="label label-quote"><i class="icon-ok icon-white"> </i></span> Freedom Mission</h4>
						<p>The number of contributions is accounted for in the same way for Freedom missions. If your contribution limit is set to 3, you can therefore not take part in more than 3 missions regardless of their type.<br>As a Freedom mission can only be a quote request, and not necessarily result in a writing job, we ask you to add an expiry date to your offer. Once the deadline has been reached, if the client hasn't selected any writers, your offer will be removed from your number of contributions.</p>
						<hr>
						<h4><span class="label label-quote-premium"><i class="icon-ok icon-white"> </i></span> Premium Quote</h4>
						<p> As this is only a quote request, the contribution limit does not apply to premium quotes. If the quote becomes a Premium mission, the best quotes will be given an exclusive deadline to take part in the Premium mission and to offer a rate again.</p>
							</div>								
							<div class="span5 offset1">
								 <h3><img width="132" height="70" src="/FO/images/niveau-badge.png" class="pull-right">Levels</h3>
									<ul class="explainLevel">
										 <li><span class="label label-level">Beginner</span></li>
										<li>No articles accepted on Edit-place yet</li>
										<li><span class="label label-level">Junior</span></li>
										<li>At least 1 article accepted on Edit-place</li>
										<li><span class="label label-level">Senior</span></li>
										<li>I have at least 5 articles approved by Edit-place. I am an approved contributor for Edit-place.</li>
									</ul>
							</div>
						</div>					
					</div>
					<div class="tab-pane" id="timing">						
						<h4><span class="label label-premium"><i class="icon-ok icon-white"> </i></span> DEADLINE TO SET YOUR RATES</h4>

						<p>
							This is the timeframe you have to take part and set your rates. Once the time has elapsed, you will no longer be able to take part in the mission. This is set by the client for Freedom missions and by Edit-place for Premium missions/quotes.
							
						</p>	 
						<h4><span class="label label-quote"><i class="icon-ok icon-white"> </i></span> DEADLINE TO SEND YOUR ARTICLE</h4>
						<p>
							From the moment you are selected, the countdown starts and you will receive an email stating how long you have left to send your article. You will also find this deadline in your ongoing contributions. If for some unforeseen reason you are unable to send your article in time, you can ask for an extension, but only if the original deadline hasn't expired. This request must remain a one-off and isn't necessarily agreed. If this is the case, the mission will be taken away from you.
						</p>	
						<h4><span class="label label-quote-premium"><i class="icon-ok icon-white"> </i></span> DEADLINE TO REWRITE/AMEND YOUR ARTICLE</h4>
						<p>
							If a rewrite/amendment is requested by the client (Freedom mission) or Edit-place (Premium mission), you will receive an email stating how long you have to change your article. You will also find this deadline in your ongoing contributions.
						 </p>

					</div>
					<div class="tab-pane" id="pricing">
						<h4><span class="label label-premium"><i class="icon-ok icon-white"> </i></span> Premium Mission</h4>
						<p>
						  A price range is offered for each premium mission.<br>
						  You then have to offer your own rate within this price range, bearing in mind that this is a key factor when selecting profiles. <br>
						  If you are selected, the rate that you have offered is the rate that you will be paid once the mission has been confirmed.<br>
						</p>
						<hr>
						<h4><span class="label label-quote"><i class="icon-ok icon-white"> </i></span> Freedom Mission</h4>
						<p>						  
						  During freedom missions, no price range is set. Therefore you have to offer your rate. </p>
						  
						<hr>
						<h4><span class="label label-quote-premium"><i class="icon-ok icon-white"> </i></span> Premium Quote</h4>
						<p>
							A premium quote may or may not come with a price range. You will find all the information on the page after you click on the "My selection" button. 
						</p>
						
						<p><strong>Note</strong>&nbsp;: Edit-Place reserves the right to change the rate offered if the article could not be written or cannot be written (already existing....)</p>

					</div>
					<div class="tab-pane" id="validation">
					<h4><span class="label label-premium"><i class="icon-ok icon-white"> </i></span> Premium Mission</h4>
					<p>
					  Edit-Place checks through the article after it has been written, and approves or rejects it, depending on whether it meets expectations or not. If it is refused, you may be asked to rewrite or amend the content. You will then have a certain amount of time to change your article and resend it, otherwise it will be automatically republished online. <br>
					  Once your article(s) is accepted, after deducting 2% charges for transfer and administrative fees, your will receive a payment credit to your account.<br>
					  Please note that the payments are processed (premium / freedom options) on 15th of the following month after your article has been accepted, and there is a charge of 8% should you choose advance payment option. There is no fee if you decide to receive your payment within the regular timeframe. Eg: If your article was accepted on 3rd September, you can choose to get your payment on 15th October with a 8% charge for advance payment, or 15th November at no charge.</p>
					<hr>
					<h4><span class="label label-quote"><i class="icon-ok icon-white"> </i></span> Freedom Mission</h4>
					<p>
					  The client proofreads your article and approves or rejects it, depending on whether or not it meets expectations.  If it is refused, you may be asked to rewrite or amend the content. You will then have a certain amount of time to change your article and resubmit it. You set the number of retakes allowed with the client. If the client deems that the editorial guidelines still are not being followed, the article may be rejected altogether and Edit-place will assess the situation.<br>
					  Once your article(s) is accepted, after deducting 2% charges for transfer and administrative fees, your will receive a payment credit to your account.<br>
					  Please note that the payments are processed (premium / freedom options) on 15th of the following month after your article has been accepted, and there is a charge of 8% should you choose advance payment option. There is no fee if you decide to receive your payment within the regular timeframe. Eg: If your article was accepted on 3rd September, you can choose to get your payment on 15th October with a 8% charge for advance payment, or 15th November at no charge.</p>
					<hr>
					<h4><span class="label label-quote-premium"><i class="icon-ok icon-white"> </i></span> Premium Quote</h4>
					<p>
					  As this is only a quote request, premium quotes do not involve article approvals or invoicing. </p>
					</div>
				</div>		
			</div>
		</div>
    </div>
 </section>