<div class="span3">
	<aside>
		<p><a id="menu_compose" class="btn btn-small btn-primary btn-block" href="/contrib/compose-mail">New message</a></p>
		<ul class="nav nav-tabs nav-stacked">
			<li id="menu_inbox"><a href="/contrib/inbox">{if $unreadCount gt 0}<span class="badge pull-right">{$unreadCount}</span>{/if}Inbox</a></li>
			<li id="menu_sentbox"><a href="/contrib/sentbox"><i id="sent_icon" style="display:none" class="icon-chevron-right pull-right"></i>Sent </a></li>
			<li id="menu_classifybox"><a href="/contrib/classifybox">{if $class_ticket_count gt 0}<span class="badge pull-right">{$class_ticket_count}</span>{/if}Folder message</a></li>
		</ul>	
	</aside>
</div>