{literal}
<script>
	function payformsubmit(ptype)
	{  
		document.payform.action ="/client/paypalpayment?paytype="+ptype;
		document.payform.submit();
		return false;
	}
</script>
{/literal}

<div class="container">
	<!-- start, status -->
	<div class="row-fluid">
		<div id="state2" class="span12">
			<ul class="unstyled">
				<li class="span3" rel="tooltip" data-original-title="Select the writer who will work on your project"><span class="writer_select">Choice of writer</span></li>
				<li class="span3" rel="tooltip" data-original-title="The writer selected is working on your project"><span class="ongoing">Ongoing work</span></li>
				<li class="span3 hightlight" rel="tooltip" data-original-title="You pay the amount of the order as a deposit"><span class="cb">Deposit</span></li>
				<li class="span3" rel="tooltip" data-original-title="Download your delivered projects"><span class="dld">Download</span></li>
			</ul>
		</div>
	</div>
	<!-- end, status -->
	
	<!-- start, Summary -->
	<section id="summary">
		<div class="row-fluid">
			<div class="span6">
				<h1><p>Mission</p> {$aoparticipation[0].title}</span></h1>
			</div>
			<div class="span3 stat">
				<p>Delivery date</p>
				<p class="num-large less24">
					{if $aoparticipation[0].articlestatus=="closed_client"}
						Closed
					{else}
						Delivered
					{/if}
				</p>
			</div>
			<div class="span2 stat">
				<p>Rate</p>
				<p class="num-large">{$aoparticipation[0].price_user_total|ceil} {if $aoparticipation[0].currency=='pound'}&pound;{else}&euro;{/if}</p> 
			</div>
			<div class="span1 stat">
				<div class="icon-comment-large" rel="tooltip" data-original-title="Comments on this mission"><a href="#comment" >{$commentcount}</a></div>
			</div>
		</div>
	</section>
	<!-- end, summary --> 

	<div class="row-fluid"> 
		{if $aoparticipation[0].premium_option=="0"}
		<div class="statusbar clearfix">
			<div class="btn-toolbar">
				<div class="btn-group">
					{if $aoparticipation[0].created_by=="FO"}
						<a class="btn btn-small" href="/client/quotes-1?article={$smarty.get.id}"><i class="icon-pencil"></i> Re-launch quote</a>
					{/if}
					{if $aoparticipation[0].articlestatus!="closed_client"}
						<a class="btn btn-small" href="/client/compose-mail?serviceid=111201092609847&object={$aoparticipation[0].title}"><i class="icon-envelope"></i> Contact Edit-place</a>
						<a class="btn btn-small" href="javascript:void(0);" onClick="CloseArticle('{$smarty.get.id}');" target="_blank"><i class="icon-remove"></i> Close quote</a>
					{/if}
				</div>
			</div>
		</div>
		{/if}
		<div class="row-fluid"> 
			<div class="span9">
			<section id="purchase">
				<div class="row-fluid">
					<div class="span12">
						<h3>Payment of deposit</h3>
						<p>Edit-place takes the amount quoted by the writer as a deposit until the the articles have been approved by the client. Edit-place will refund you the money if the order is rejected.*</p>
					</div>
				</div>
				<div class="row-fluid">
					<br>
					<table class="table table-bordered table-hover span8 offset2">
						<thead>
							<tr>
								<th colspan=3><h4>ORDER</h4></th>
							</tr>
						</thead>
						<tr><td colspan=3 class="span6">{$aoparticipation[0].title}</td></tr>
						<tr><td class="span6"></td><td class="span3 price">Price exc. VAT</td><td class="span3 price">{$aoparticipation[0].price_user|ceil} {if $aoparticipation[0].currency=='pound'}&pound;{else}&euro;{/if}</td></tr>
						{if $aoparticipation[0].client_type!="personal"}
						<tr>
							<td class="span6"></td>
							<td class="span3 price">VAT inc.</td>
							<td class="span3 price">{$tax|zero_cut:2} {if $aoparticipation[0].currency=='pound'}&pound;{else}&euro;{/if}</td>
						</tr>
						{/if}
						{math assign="total" equation='x+y' x=$aoparticipation[0].price_user_total|ceil y=$tax"} 
						<tr class="info">
							<td class="span6"></td>
							<td class="span3 price totalprice">Total to pay</td>
							<td class="span3 price totalprice">{$total|zero_cut:2} GBP inc. tax</td> 
						</tr>
					</table>

					<form method="POST" name="payform">
						<div class="span8 offset2">
							<div class="pull-center">
								{if $aoparticipation[0].articlestatus!="closed_client"}
								<hr>
								<h4>SELECT PREFERRED PAYMENT METHOD</h4>
									{if $first_name==""}
										<div class="btn btn-large" data-target="#profile-update" data-toggle="modal">Paypal</div>
										<div class="btn btn-large" data-target="#profile-update" data-toggle="modal">CB</div>
									{else} 
										<div class="btn btn-large" onClick="payformsubmit('PP');">Paypal</div>
										<div class="btn btn-large" onClick="payformsubmit('CC');">CB</div>
									{/if}
								{/if}
							</div>
						</div>
						<input type="hidden" name="delivery" id="delivery" value="{$smarty.get.id}" />
						<input type="hidden" name="article" id="article" value="{$aoparticipation[0].article_id}" />
						<input type="hidden" name="amount_topay" id="amount_topay" value="{$total}" />
						<input type="hidden" name="amount" id="amount" value="{$aoparticipation[0].price_user_total|ceil}" />
						<input type="hidden" name="currency" id="currency" value="{$aoparticipation[0].currency}" />
					</form>
				</div>
			</section>
		</div>
		<div class="span3">
			<!--  right column  -->
			<aside>
				<div class="aside-bg">
					{if $aoparticipation[0].premium_option=="0"}
						<div class="editor-price">
							<p class="quote-price">Total Price :<strong> {$aoparticipation[0].price_user_total|ceil} {if $aoparticipation[0].currency=='pound'}&pound;{else}&euro;{/if}</strong></p>
							<ul class="unstyled stripe">
								<li>Writer tariff  : {$aoparticipation[0].price_user|zero_cut:2} {if $aoparticipation[0].currency=='pound'}&pound;{else}&euro;{/if}</li>
								<li>Edit-place fees included : {$aoparticipation[0].ep_percent|zero_cut:2}%</li>
							</ul>
						</div> 
					{/if}
					<div id="selected-editor" class="aside-block">
						<div class="editor-container">
							<h4>Your contact</h4>
							<a class="imgframe-large" onclick="loadcontribprofile('{$contact[0].identifier}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">
							<img src="{$contact[0].profilepic}" alt="{$contact[0].name}"></a>
							<p class="editor-name"><a onclick="loadcontribprofile('{$contact[0].identifier}');" role="button" data-toggle="modal" data-target="#viewContribProfile" style="cursor:pointer;">{$contact[0].name}</a></p>
							<a href="/client/compose-mail?clientid={$contact[0].identifier}&ord=y1s" class="btn btn-small">Contact {$contact[0].first_name|ucfirst}</a>
							<address>
								<i class="icon-phone"></i> +{$contact[0].phone_number}<br>
								<a href="mailto:{$contact[0].email}"><i class="icon-email"></i> {$contact[0].email}</a>
							</address>
						</div>
					</div>
					
					{if $customerstrust|@count>0}
					<div id="we-trust" class="aside-block">
						<h4>THE WRITER HAS ALREADY WORKED WITH</h4>
						<ul class="unstyled">
							{foreach from=$customerstrust item=clogo key=ckey}
								<li><img src="{$clogo}" rel="tooltip" data-original-title="{$ckey|utf8_decode}" data-placement="left"></li>
							{/foreach}
						</ul>
					</div>
					{/if}
					
					<div class="aside-block" id="garantee">
						<h4>YOUR GUARANTEES</h4>

						<dl>
							<dt><span class="umbrella"></span>Edit-place is your mediator</dt>
							<dd>In the event of a dispute/issue (delay in delivery, article rewrites, refund…)</dd>
							<dt><span class="locked"></span>Secure payment</dt>
							<dd>Our online payment solution guarantees you a hassle-free transaction</dd>
						</dl>
					</div>
				</div>
			</aside>  
		</div>
	</div>
</div>
 
<!-- contrib profile -->
<div id="viewContribProfile" class="modal container hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">Writer's profile</h3>
	</div>
	<div class="modal-body">
		<div id="userprofile">
	
		</div>
	</div>
</div>

<!-- Client profile update -->
<div id="profile-update" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 id="myModalLabel">COMPLETE YOUR PROFILE</h3>
	</div>
	<div class="modal-body">
		<p>Please complete your profile to Pay and download.</p>
		<p><a href="/client/profile?from=payment&article={$smarty.get.id}">Complete your profile</a></p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	</div>
</div>