<section id="prebidding" class="clearfix">
	<div class="span9 offset1">
		<h2>
			{if $participationcount>1}
				{$participationcount} writers have proposed a tariff
			{else}
				{$participationcount} writer has proposed a tariff
			{/if}
		</h2>
		<h3 class="sectiondivider pull-center"><span>They have written for...</span></h3>
		<br />
			{foreach from=$customerstrust item=clogo key=ckey}
				<img src="{$clogo}" rel="tooltip" data-original-title="{$ckey|utf8_decode}" data-placement="top">
			{/foreach}
		<hr /><br>
		<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">See quotes</button>
	</div>
</section>
