<section class="dashit wow fadeInLeft" id="clientwelove">
	<div class="container padding">
		<div class="center-block">
			<h4>Our clients</h4>
			<ul>
				<li class="partnerslogo groupon"></li>
				<li class="partnerslogo expedia"></li>
				<li class="partnerslogo homeway"></li>
				<li class="partnerslogo jetcost"></li>
			</ul>
		</div>
	</div>
</section>

<section class="dashit" id="seosem">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-6">   
				<div class="center-block">
  <img src="/FO/images/imageB3/svg/seo.svg" id="seo" class="img-center img-responsive wow bounceIn" data-wow-delay="100ms" data-wow-offset="300" width="500"></div>
      </div>
  <div class="col-xs-12 col-md-6">
        <h2>Create SEO content
      <small>Increase traffic and time spent on your site</small>
      </h2>
      <p>Create content using keywords with high potential in Google</p>
      <ul>
        <li>URL Ranking</li>
        <li>Plagiarism check</li>
        <li>Subjects with high traffic potential</li>
        <li>Keyword density - long tail</li>
      </ul>
  
  </div>
</div>
	<div class="row">
	<div class="col-xs-12 col-md-4 col-md-offset-1">
	<h2 class="sem">SMO content
      <small>Readers sharing your content</small>
      </h2>
      <ul>
        <li>Blog animation</li>
        <li>Linkbaiting</li>
        <li>Animation of social networks</li>
        <li>Picture integration</li>
      </ul>
	</div>
  <div class="col-xs-12 col-md-7">  
  <div class="center-block">
  <img src="/FO/images/imageB3/svg/sem.svg" class="img-center img-responsive wow rotateInUpLeft" width="600"  data-wow-offset="200" data-wow-delay="100ms">
  </div> 
      </div>
	</div>
</div>  
    
</section>

<section class="dashit" id="translation"> 
	<div class="container padding">
		<div class="center-block">
			<h2>Translation
				<small>Increase traffic on all your sites</small>
			</h2>
			<div id="flag-list">
				<ul class=" wow fadeInLeft">
					<li><img src="/FO/images/imageB3/flag/france.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/uk.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/us.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/germany.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/spain.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/brasil.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/china.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/denmark.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/finland.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/italy.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/japan.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/norway.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/poland.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/portugal.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/russia.png" width="512" height="295" class="img-responsive"></li>
					<li><img src="/FO/images/imageB3/flag/sweden.png" width="512" height="295" class="img-responsive"></li>
				</ul>
			</div>
			<h4 class="world">Adaptation and localization of the content in more than 
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">30 languages</a>.	
			<div class="lang-list dropdown-menu pull-right" role="menu" aria-labelledby="dLabel" style="height:269px;overflow-y:scroll">
						<table>
							<tbody><tr>
								<td>
									ENGLISH
									<ul class="unstyled" style="list-style:none;text-align:left">
										<li><img src="/FO/images/shim.png" class="flag flag-gb"> ENGLISH English (UK)</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-us"> English (US)</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-au"> Australia</li>
									</ul> 
									SPANISH
									<ul class="unstyled" style="list-style:none;text-align:left">
										<li><img src="/FO/images/shim.gif" class="flag flag-ar"> Spanish (Argentina)</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-es"> Spanish (Spain)</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-co"> Spanish (Spain)</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-cl"> Chile</li>
									</ul>
									ARABIC
									<ul class="unstyled" style="list-style:none;text-align:left">
										<li><img src="/FO/images/shim.gif" class="flag flag-dz"> ARABIC Algerian</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-ma"> Moroccan</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-ps"> Palestinian</li>
										<li><img src="/FO/images/shim.gif" class="flag flag-tn"> Tunisian</li>
									</ul>   
								</td>
								<td>
									<ul class="unstyled" style="list-style:none;text-align:left">
										<li><img src="/images/shim.gif" class="flag flag-de"> German</li>
										<li><img src="/images/shim.gif" class="flag flag-cn"> Chinese</li>
										<li><img src="/images/shim.gif" class="flag flag-dk"> Danish</li>
										<li><img src="/images/shim.gif" class="flag flag-fr"> French</li>
										<li><img src="/images/shim.gif" class="flag flag-fi"> Finnish</li>
										<li><img src="/images/shim.gif" class="flag flag-gr"> Greek</li>
										<li><img src="/images/shim.gif" class="flag flag-it"> Italian</li>
										<li><img src="/images/shim.gif" class="flag flag-jp"> Japanese</li>
										<li><img src="/images/shim.gif" class="flag flag-nl"> Japanese</li>
										<li><img src="/images/shim.gif" class="flag flag-no"> Norwegian</li>
										<li><img src="/images/shim.gif" class="flag flag-pl"> Polish</li>
										<li><img src="/images/shim.gif" class="flag flag-pt"> Portuguese</li>
										<li><img src="/images/shim.gif" class="flag flag-ru"> Russian</li>
										<li><img src="/images/shim.gif" class="flag flag-se"> Swedish</li>
									</ul>
								</td>
							</tr>
						</tbody></table>
					</div>		
			</h4>
			<p>Highly skilled native experts in your sector.<br />Localization including long tail keywords adapted to any country and style.</p>
			<hr>
			<p><a href="/client/quotes-1" class="btn btn-primary btn-lg" role="button">Check our prices</a></p>
		</div>
	</div>
</section>

<section class="dashit"  id="desc">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-6 wow fadeInLeft">   
				<h2>Product descriptions
				<small>Increase sales through SEO</small> 
				</h2>
				<p>Exclusive content can be delivered within 72 hrs.<br>
				Content that best suits your brand image.<br>
				Your photo collection in safe hands with our dedicated team.</p>
			</div>
			<div class="col-xs-12 col-md-6">
				<div class="center-block">
					<img src="/FO/images/imageB3/svg/note.svg" class="img-center img-responsive">
				</div>
			</div>
		</div>
	</div>    
</section>

<section class="dashit" id="strategy">
	<div class="container padding">
		<div class="row">
			<div class="col-xs-12 col-md-7"> 
				<div class="center-block">  
					<h2>Content strategy</h2>
					<img src="/FO/images/imageB3/svg/strategy.svg" class="img-center img-responsive" width="230">
					<p><strong>Topic suggestions, audits and content recommandations.</strong><br>
					Editorial brief, benchmark of your competitors, author ranks, dedicated tech developments
					</p>
					<!--<a href="#" class="btn btn-default btn-lg" role="button">En savoir plus</a>-->
				</div>
			</div>
			<div class="col-xs-12 col-md-4 col-md-offset-1">
				<div class="center-block">
					<div class="news-block">
						<h2>News <small>Increase your traffic on Google news</small></h2>
						<img src="/FO/images/imageB3/svg/news.svg" class="img-center img-responsive" width="90" height="90">
						<p>Using tools developed internally – suggesting content topics and producing them in less than 40 mins. Our writers are available 24/7</p>
					</div>
				</div>
			</div>
		</div>
	</div>    
</section> 

<section class="dashit" id="interview">
    <div class="container padding">
        <div class="row">
  <div class="col-xs-12 col-md-4"> <h2>Your questions <small>Our answers</small></h2> </div>
   <div class="col-xs-12 col-md-4">
   <a href="https://www.youtube.com/watch?v=jiYF9svxlUg" data-toggle="lightbox" data-width="940" class="wow flipInY" data-wow-offset="100" data-wow-delay="100ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/kasia.jpg" width="300" height="167" class="img-responsive"></div>Choose the right subject
   <span class="who">Kasia, Project manager Polish</span></a></div>
   <div class="col-xs-12 col-md-4">
   <a href="https://www.youtube.com/watch?v=M9nxXct-2rs" data-toggle="lightbox" data-width="940" class="wow flipInY" data-wow-offset="100" data-wow-delay="200ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/alix.jpg" width="300" height="167" class="img-responsive"></div>
   Complement agency services<span class="who">Alix, Multilingual site launch co-ordinator</span></a>
   </div>
   <div class="col-xs-12 col-md-4">
   <a href="https://www.youtube.com/watch?v=0Dhu4AmfHrM" data-toggle="lightbox" data-width="940" class="wow flipInY" data-wow-offset="100" data-wow-delay="300ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/santiago.jpg" width="300" height="167" class="img-responsive"></div>
   Expand your site internationally<span class="who">Santiago, Project manager lead Spanish</span></a>
   </div>
       <div class="col-xs-12 col-md-4">
   <a href="https://www.youtube.com/watch?v=2fWEzNA330U" data-toggle="lightbox" data-width="940" class="wow flipInY" data-wow-offset="100" data-wow-delay="400ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/alex.jpg" width="300" height="167" class="img-responsive"></div>
   Improve your SEO rankings  <span class="who">Alex, Project manager English</span></a>
   </div>
      <div class="col-xs-12 col-md-4">
   <a href="https://www.youtube.com/watch?v=fZXAjDPuV88" data-toggle="lightbox" data-width="940" class="wow flipInY" data-wow-offset="100" data-wow-delay="500ms"><div class="thumb"><span class="glyphicon glyphicon-play"></span> <img src="/FO/images/imageB3/interview/emilie.jpg" width="300" height="167" class="img-responsive"></div>
   Have your product descriptions sooner <span class="who">Emilie, Project manager Fashion and travel projects</span></a>
   </div>
  </div>
  </div>
</section>




<section class="dashit" id="morecontent">
	<div class="container padding">
		<div class="center-block"><h2>More than content</h2></div>
		<div class="row">
			<div class="col-xs-12 col-md-7">
				<div class="row">
					<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.1s">
						<div class="center-block">
							<img src="/FO/images/imageB3/svg/bo.svg" class="img-center img-responsive" width="90">
							<p class="title">Integration of content in your back office system</p>
						</div>
					</div>
					<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.2s">
						<div class="center-block">
							<img src="/FO/images/imageB3/svg/pencil.svg" class="img-center img-responsive" width="90">
							<p class="title"> Spell check</p>
						</div>
					</div>
					<div class="center-block">
						<div class="col-xs-12 col-md-4 wow fadeInLeft" data-wow-delay="0.3s">
							<img src="/FO/images/imageB3/svg/countdown.svg" class="img-center img-responsive" width="90">
							<p class="title">On-time delivery guaranteed</p>
						</div>
					</div>
				</div>
				<hr> 
				<h4>We also offer </h4>
				<ul>
					<li>A dedicated account manager and tech team</li>
					<li>Specialized writers with proven experience in your sector</li>
					<li>Full intellectual property rights transferred for content</li>
					<li>Content integration in your CMS</li>
					<li>Animation of your homepage</li>
				</ul>
			</div>
			<div class="col-xs-12 col-md-4 col-md-offset-1">
				<div class="news-block">
						<img src="/FO/images/imageB3/author-rank.jpg" width="370" height="211" alt="Author Rank" class="img-responsive">
						<h3>Author rank</h3>
					<p>Personalise your pages in Google's results page by letting our team implement Google+/Author rank</p>
				</div>
			</div>
		</div>
	</div>    
</section>

<!--<section class="dashit" id="callus">
	<div class="container padding">
		<div class="center-block">
			<h4>Parlons de votre projet</h4>
			<h2>01 85 08 40 14</h2>
			<p>Prix d'un appel local. Lundi au vendredi de 10h à 18h</p>
			<a href="/index/contact" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-envelope"></span> Contactez nous</a>
		</div>
	</div>
</section>-->
