<section id="tagline"> 
 <div class="container">
   <p>Writing, Translation and SEO of exclusive online content</p>
 </div>
</section>

<section id="content"> 
	<div class="container">
		<div class="row-fluid">
			<div class="span12">
				<h3>Our clients</h3>
				<hr>
				<div class="mod media">
					<a  class="pull-right" target="_blank" href="http://www.aufeminin.fr/">
						<img class="media-object"  src="/FO/images/capture%20dcran%202011-05-25%20%2018.23.13.png" alt="Aufeminin.fr" title="Aufeminin.fr" width="144" height="34"/>
					</a>
				
					<div class="media-body">
						<h4 class="media-heading">Aufeminin</h4>
						<p class="org muted">www.aufeminin.fr</p>
						magazine f&eacute;minin sur Internet
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" target="_blank" href="http://www.kelkoo.fr/">
						<img class="media-object"  src="/FO/images/ref-kelkoo.png" alt="logo Kelkoo" title="logo Kelkoo" height="61"/>
					</a>
				
					<div class="media-body">
						<h4 class="media-heading">Kelkoo</h4>
						<p class="org muted">www.kelkoo.fr</p>
						Pionnier des comparateurs de prix depuis 1999
					</div>
				</div>
				<div class="mod media">
						
					<a  class="pull-right" href="http://www.condenast.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202011-05-25%20%2018.19.44.png" border="0" alt="Condenast logo" title="condenast.com" width="144" height="58" /></a>
					<div class="media-body">
						<h4 class="media-heading">Condé Nast</h4>
						<p class="org muted">www.condenast.com</p>
						Groupe de Presse
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.boursorama.com/" target="_blank"><img  src="/FO/images/ref-bours.png" border="0" alt="Boursorama" title="Boursorama" width="170" height="49" /></a> 
					<div class="media-body">
						<h4 class="media-heading">Boursorama</h4>
						<p class="org muted">www.boursorama.com</p>
						Leader fran&ccedil;ais de l'information financi&egrave;re en ligne
					</div>	
				</div>
				<div class="mod media"> 
					<a  class="pull-right" href="http://www.primavista.fr/" target="_blank"><img  src="/FO/images/ref-prima.png" border="0" alt="Groupe  Primavista" title="Groupe Primavista" width="170" height="49" /></a>
					<div class="media-body">
						<h4 class="media-heading">Groupe Primavista</h4>
						<p class="org muted">www.primavista.fr</p>
						Contenu &eacute;ditorial online et offline sur l'univers b&eacute;b&eacute;
					</div>
				</div>
				<div class="mod media"> 
					<a  class="pull-right" href="http://www.ebookers.fr/" target="_blank"><img  src="/FO/images/ref-ebook.png" border="0" alt="ebookers.fr" title="ebookers.fr" width="170" height="52" /></a> 
					<div class="media-body">
						<h4 class="media-heading">Ebookers</h4>
						<p class="org muted">www.ebookers.fr</p> 
						Agence de voyage en ligne
					</div>	
					
				</div>
				 <div class="mod media">  
					<a  class="pull-right" href="http://www.korben-esolutions.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202011-05-25%20%2018.21.33.png" border="0" alt="Korben logo" title="Korben logo" width="144" height="54" /></a>
					<div class="media-body">
						<h4 class="media-heading">Agence Korben E-Solution</h4>
						<p class="org muted">www.korben-esolutions.com</p>
						Agence du groupe de pr&ecirc;t &agrave; porter Beaumanoir
					</div>
					
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.adverline.fr/" target="_blank"><img  src="/FO/images/ref-adver.png" border="0" alt="Adverline" title="Adverline" width="170" height="49" /></a>
					<div class="media-body">
						<h4 class="media-heading">Adverline</h4>
						<p class="org muted">www.adverline.fr</p>
						R&eacute;gie publicitaire sur Internet
					</div>
				</div>    
				<div class="mod media"> 
					 <a  class="pull-right" href="http://www.yahoo.fr/" target="_blank"><img  src="/FO/images/ref-yahoo.png" border="0" alt="Yahoo! France" title="Yahoo! France" width="170" height="55" /></a>
					 <div class="media-body">
						<h4 class="media-heading">Yahoo</h4>
						<p class="org muted">www.yahoo.fr</p>
						Portail international d'information et actualit&eacute;s
					</div>
				</div>
				 <div class="mod media"> 
					<a  class="pull-right" href="http://vacances.seloger.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202010-05-05%20%2012.24.03.png" border="0" alt="logo se loger vacances" title="logo se loger vacances" width="170" height="73" /></a>
					<div class="media-body">
						<h4 class="media-heading">Seloger Holidays</h4> 
						<p class="org muted">www.seloger.fr</p> 
						Site internet de petites annonces ventes et locations immobili&egrave;res
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.archipelago-publishing.com/" target="_blank"><img  src="/FO/images/ref-arch.png" border="0" alt="Archipelago Publishing" title="Archipelago Publishing" width="170" height="49" /></a>
					<div class="media-body">
						<h4 class="media-heading">Archipelago Publishing</h4> 
						<p class="org muted">www.archipelago-publishing.com</p>
						Plateforme de publication et de mon&eacute;tisation de contenu sur Internet
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.bellesdemeures.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202010-05-26%20%2011.15.36.png" border="0" alt="logo Belles Demeures" title="logo Belles Demeures" width="175" height="38" /></a>
					<div class="media-body">
						<h4 class="media-heading">Belles Demeures</h4>
						<p class="org muted">www.bellesdemeures.fr</p>
						Site internet de petites annonces ventes et locations immobili&egrave;res de luxe
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.shopping.com/" target="_blank"><img  src="/FO/images/logo-shopping.png" border="0" alt="Shopping.com" title="Shopping.com" width="175" height="47" /></a>
					<div class="media-body">
						<h4 class="media-heading">Shopping</h4>
						<p class="org muted">www.shopping.com</p>
						Comparateur de prix sur internet
					</div>
				 </div>
				 <div class="mod media"> 
					<a  class="pull-right" href="http://www.cibleweb.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202010-05-03%20%2009.52.50.png" border="0" alt="cibleweb logo" title="cibleweb logo" width="160" height="70" /></a>
					<div class="media-body">
						<h4 class="media-heading">Cibleweb</h4>
						<p class="org muted">www.cibleweb.fr</p>
						Agence de gestion de vos flux pour tous les comparateurs internet avec sa solution iziflux
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.commentcamarche.net/" target="_blank"><img  src="/FO/images/capture%20dcran%202011-05-25%20%2018.20.20.png" border="0" alt="Comment ça marche.net" title="Comment ça marche.net" width="144" height="46" /></a>
					<div class="media-body">
						<h4 class="media-heading">Comment &ccedil;a marche</h4>
						<p class="org muted">www.commentcamarche.net</p>
						Site web de vulgarisation informatique
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.lastminute.com/" target="_blank"><img  src="/FO/images/site_master_top_logo_lb2.gif" border="0" alt="lastminute logo" title="lastminute logo" width="290" height="71" /></a>
					<div class="media-body">
						<h4 class="media-heading">Lastminute.com</h4>
						<p class="org muted">www.lastminute.com</p>
						Agence de voyage en ligne
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.eperfconsulting.com/" target="_blank"><img  src="/FO/images/capture%20dcran%202010-08-23%20%2015.01.17.png" border="0" alt="e perf consulting logo" title="e perf consulting " width="144" height="58" /></a>
					<div class="media-body">
						<h4 class="media-heading">E perf Consulting</h4>
						<p class="org muted">www.eperfconsulting.com</p>
						Des artisans-experts SEO, au service de votre réfèrencement naturel
					</div>
				</div>
				<div class="mod media"> 
					<a  class="pull-right" href="http://www.opodo.fr/" target="_blank"><img  src="/FO/images/capture%20dcran%202011-05-25%20%2018.11.23.png" border="0" alt="opodo logo" title="Logo Opodo" width="144" height="59" /> </a>
					<div class="media-body">
						<h4 class="media-heading">Opodo</h4>
						<p class="org muted">www.opodo.fr</p>
						Agence de voyage en ligne 
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.cdiscount.com/" target="_blank"><img  src="/FO/images/logo-cdiscount.png" border="0" alt="Cdiscount logo" title="Cdiscount" width="144" height="58" /></a>
					<div class="media-body">
						<h4 class="media-heading">Cdiscount</h4>
						<p class="org muted">www.cdiscount.com</p>
						Site e-commerce de vente de produits g&eacute;n&eacute;ralistes
					</div>
				</div>
				<div class="mod media">
					<a  class="pull-right" href="http://www.businesscoot.com/fr/" target="_blank"><img  src="/FO/images/logo_businesscoot.jpg" border="0" alt="businesscoot logo" title="businesscoot" /></a>
					<div class="media-body">
						<h4 class="media-heading">Businesscoot</h4>
						<p class="org muted">www.businesscoot.com/fr/</p>
						Votre fournisseur d'informations sectorielles et  d'&eacute;tudes de march&eacute;.
					</div>
				</div>
			</div>
			<p>&nbsp;</p>
		</div>	 
	</div>   
</section>